/*****************************************************************************
* Copyright 2013 Nxtr Automotive, All Rights Reserved.
* Nxtr Confidential
*
* Module File Name  : ePWM.c
* Module Description: eTPWM Complex Device Driver (Not to be regenerated by RTE generator)
* Product           : Gen II Plus - EA3.0
* Author            : Owen Tosh
*****************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of version logging area >>                DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
 /*---------------------------------------------------------------------------
* Version Control:
* Date Created:      Thu Jan 31 13:14:15 2013
* %version:          2 %
* %derived_by:       nzx5jd %
* %date_modified:    Mon Mar 11 11:10:56 2013 %
*---------------------------------------------------------------------------*/
/********************************************************************************************************************
CHANGE HISTORY:
Date      Rev      Author    Change Description                                                                 SCR #
--------  -------  --------  ---------------------------------------------------------------------------------  -----
02/04/13  1        Selva     Initial Version
03/11/13  2        OT        Reversed active state for ePWM1-3 (anomaly 4605)
********************************************************************************************************************/
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of version logging area >>                  DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of include and declaration area >>        DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/


#include "ePwm.h"
#include "CDD_Data.h"
#include "CalConstants.h"

#define D_PHSAIDX_CNT_U16  0U
#define D_PHSBIDX_CNT_U16  1U
#define D_PHSCIDX_CNT_U16  2U


/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of include and declaration area >>          DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

#define EPWM_START_SEC_CODE
#include "MemMap.h"
 
/**********************************************************************************************************************
 *
 * Runnable Entity Name: ePWM_Init1
 *
 *---------------------------------------------------------------------------------------------------------------------
 *
 * Executed at ECU Startup 
 *
 *********************************************************************************************************************/
 
FUNC(void, EPWM_CODE) ePWM_Init1(void)
{
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of runnable implementation >>             DO NOT CHANGE THIS COMMENT!
 * Symbol: ePWM_Init1
 *********************************************************************************************************************/

	
	/* Initialize ePWM1 */
	
	ePWM1->TBCTL = (2U)         /* Counter Mode:                               Up-Down */
				 | (1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | (0U << 3U)   /* Use shadow period register:                 Enabled */
				 | (1U << 4U)   /* Sync Output Select:                         CTR = zero */
				 | (0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | (0U << 10U)  /* Clock Prescale:                             1:1 */
				 | (1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM1->TBPRD = 2499U; /* Init with period of 62.5 us (80MHz/16kHz = 5000 counts, use half for up/down mode) */
	
	ePWM1->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM1->CMPA = 2499U; /* Init duty cycle of 0% */
	
	ePWM1->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | (0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM1->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | (0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | (2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | (1U << 6U)   /* CTR = CMPA, decrementing:  Clear */
				  | (0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | (0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM1->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | (2U << 2U)   /* Polarity Select:  Invert B */
				 | (0U << 4U)   /* In Mode:          Use A for both RED and FED outputs */
				 | (0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM1->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM1->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM1->PCCTL = 0U; /* Disable chopper */
	
	ePWM1->TZCTL = 0x0FFF; /* Do nothing on all trip-zone conditions */
	
	ePWM1->ETSEL= 0U; /* Disable all events */
	
	
	/* Initialize ePWM2 */
	
	ePWM2->TBCTL = (2U)         /* Counter Mode:                               Up-Down */
				 | (1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | (0U << 3U)   /* Use shadow period register:                 Enabled */
				 | (0U << 4U)   /* Sync Output Select:                         Sync In */
				 | (0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | (0U << 10U)  /* Clock Prescale:                             1:1 */
				 | (1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM2->TBPRD = 2499U; /* Init with period of 62.5 us (80MHz/16kHz = 5000 counts, use half for up/down mode) */
	
	ePWM2->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM2->CMPA = 2499U; /* Init duty cycle of 0% */
	
	ePWM2->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | (0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM2->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | (0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | (2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | (1U << 6U)   /* CTR = CMPA, decrementing:  Clear */
				  | (0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | (0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM2->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | (2U << 2U)   /* Polarity Select:  Invert B */
				 | (0U << 4U)   /* In Mode:          Use A for both RED and FED outputs */
				 | (0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM2->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM2->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM2->PCCTL = 0U; /* Disable chopper */
	
	ePWM2->TZCTL = 0x0FFF; /* Do nothing on all trip-zone conditions */
	
	ePWM2->ETSEL= 0U; /* Disable all events */
	
	
	/* Initialize ePWM3 */
	
	ePWM3->TBCTL = (2U)         /* Counter Mode:                               Up-Down */
				 | (1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | (0U << 3U)   /* Use shadow period register:                 Enabled */
				 | (0U << 4U)   /* Sync Output Select:                         Sync In */
				 | (0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | (0U << 10U)  /* Clock Prescale:                             1:1 */
				 | (1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM3->TBPRD = 2499U; /* Init with period of 62.5 us (80MHz/16kHz = 5000 counts, use half for up/down mode) */
	
	ePWM3->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM3->CMPA = 2499U; /* Init duty cycle of 0% */
	
	ePWM3->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | (0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM3->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | (0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | (2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | (1U << 6U)   /* CTR = CMPA, decrementing:  Clear */
				  | (0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | (0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM3->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | (2U << 2U)   /* Polarity Select:  Invert B */
				 | (0U << 4U)   /* In Mode:          Use A for both RED and FED outputs */
				 | (0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM3->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM3->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM3->PCCTL = 0U; /* Disable chopper */
	
	ePWM3->TZCTL = 0x0FFF; /* Do nothing on all trip-zone conditions */
	
	ePWM3->ETSEL = 0U; /* Disable all events */
	
	
	/* Initialize ePWM4 */
	
	ePWM4->TBCTL = (0U)         /* Counter Mode:                               Up */
				 | (1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | (0U << 3U)   /* Use shadow period register:                 Enabled */
				 | (0U << 4U)   /* Sync Output Select:                         Sync In */
				 | (0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | (0U << 10U); /* Clock Prescale:                             1:1 */
	
	ePWM4->TBPRD = 65535U; /* Init with max possible period */
	
	ePWM4->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM4->CMPA = 2499U; /* Init with trigger offset of zero */
	
	ePWM4->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | (0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM4->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | (0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | (0U << 4U)   /* CTR = CMPA, incrementing:  Do Nothing */
				  | (0U << 6U)   /* CTR = CMPA, decrementing:  Do Nothing */
				  | (0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | (0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM4->DBCTL = 0U; /* Disable deadband generator */
	
	ePWM4->PCCTL = 0U; /* Disable chopper */
	
	ePWM4->TZCTL = 0x0FFF; /* Do nothing on all trip-zone conditions */
	
	ePWM4->ETSEL = (0U << 3U)   /* Interrupt Enable:  Disabled */
				 | (4U << 8U)   /* SOCA Select:       CTR = CMPA, incrementing */
				 | (1U << 11U)  /* SOCA Enable:       Enabled */
				 | (1U << 12U)  /* SOCB Select:       CTR = zero */
				 | (1U << 15U); /* SOCB Enable:       Enabled */
	
	ePWM4->ETPS = (1U << 8U)   /* SOCA Period:  Generate SOCA on every SOCA event */
				| (1U << 12U); /* SOCB Period:  Generate SOCB on every SOCB event */
	
	
	/* Initialize ePWM7 */
	
	ePWM7->TBCTL = (0U)         /* Counter Mode:                               Up */
				 | (1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | (0U << 3U)   /* Use shadow period register:                 Enabled */
				 | (0U << 4U)   /* Sync Output Select:                         Sync In */
				 | (0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | (0U << 10U); /* Clock Prescale:                             1:1 */
	
	ePWM7->TBPRD = 65535U; /* Init with max possible period */
	
	ePWM7->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM7->CMPA = k_PwmRelay_Cnt_u16; /* Initialized with a cal */
	
	ePWM7->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | (0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM7->AQCTLB = (1U)         /* CTR = zero:                Clear */
				  | (0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | (2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | (0U << 6U)   /* CTR = CMPA, decrementing:  Do Nothing */
				  | (0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | (0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM7->DBCTL = 0U; /* Disable deadband generator */
	
	ePWM7->PCCTL = 0U; /* Disable chopper */
	
	ePWM7->TZCTL = 0x0FFF; /* Do nothing on all trip-zone conditions */
	
	ePWM7->ETSEL = 0U; /* Disable all events */
	
	
	/* Disable PWM modules 1-3 initially */
	
	ePWM_DisableOutputs();
	
	
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of runnable implementation >>               DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
	
}



/**********************************************************************************************************************
 *
 * Runnable Entity Name: ePWM_Per1
 *
 *---------------------------------------------------------------------------------------------------------------------
 *
 * Executed if at least one of the following trigger conditions occurred:
 *   - triggered on Motor Control ISR
 *
 **********************************************************************************************************************
 *
 * Input Interfaces:
 * =================
 *   None
 *
 * Output Interfaces:
 * ==================
 *   None
 *
 *********************************************************************************************************************/

FUNC(void, EPWM_CODE) ePWM_Per1(void)
{
/**********************************************************************************************************************
* DO NOT CHANGE THIS COMMENT!           << Start of runnable implementation >>             DO NOT CHANGE THIS COMMENT!
* Symbol: ePWM_Per1
*********************************************************************************************************************/
	
	
	VAR(uint16, AUTOMATIC) halfPWMPeriod_Cnt_T_u16;
	
	
	/* Update ePWM duty cycles and periods */
	
	ePWM1->CMPA = ((CDD_PWMPeriod_Cnt_G_u16 - CDD_DCPhsComp_Cnt_G_u16[D_PHSAIDX_CNT_U16]) / 2U);	
	ePWM2->CMPA = ((CDD_PWMPeriod_Cnt_G_u16 - CDD_DCPhsComp_Cnt_G_u16[D_PHSBIDX_CNT_U16]) / 2U);
	ePWM3->CMPA = ((CDD_PWMPeriod_Cnt_G_u16 - CDD_DCPhsComp_Cnt_G_u16[D_PHSCIDX_CNT_U16]) / 2U);
	halfPWMPeriod_Cnt_T_u16 = (uint16)(CDD_PWMPeriod_Cnt_G_u16/ 2U);
	
	ePWM1->TBPRD = (halfPWMPeriod_Cnt_T_u16); 
	ePWM2->TBPRD = (halfPWMPeriod_Cnt_T_u16); 
	ePWM3->TBPRD = (halfPWMPeriod_Cnt_T_u16);
	
	
	/* Update ADC trigger points */
	
	ePWM4->CMPA = ((uint16)(((sint16)(halfPWMPeriod_Cnt_T_u16)) - k_ADCTrig1Offset_Cnt_s16));
	
	
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of runnable implementation >>               DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
}

#define EPWM_STOP_SEC_CODE
#include "MemMap.h"

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of function definition area >>            DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
 
/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of function definition area >>              DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/