/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.06 */
/* configuration read from: C:\Users\pznywf\AppData\Local\Temp\~cfg4_301_EPS.ecuc.arxml.oil */
/* generation at  : Tue Jul 19 18:16:23 2016 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#ifndef _OS_TRUSTFCT_H_
#define _OS_TRUSTFCT_H_

/* Trusted Functions */

#define NtWrapS_NvMProxy_Init 0
void TRUSTED_NtWrapS_NvMProxy_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Rte_Start 1
void TRUSTED_NtWrapS_Rte_Start(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_PwmCdd_Init 2
void TRUSTED_NtWrapS_PwmCdd_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Adc2_Init1 3
void TRUSTED_NtWrapS_Adc2_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Wdg_TMS570LS3x_Init 4
void TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_WdgM_Init 5
void TRUSTED_NtWrapS_WdgM_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Adc_Init 6
void TRUSTED_NtWrapS_Adc_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_XcpWriteAp0 7
void TRUSTED_TWrapS_XcpWriteAp0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_ProcessF0FF 8
void TRUSTED_NtWrapS_ProcessF0FF(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8* os_arg_t_SrvcData_Cnt_T_u08;
   uint16 os_arg_RequestDataIdx_Cnt_T_u16;
} osTFArgType_NtWrapS_ProcessF0FF;

#define NtWrapS_StaMd_Init1 9
void TRUSTED_NtWrapS_StaMd_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_uDiagVIM_RednRpdShtdn 10
void TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_uDiagECC_RednRpdShtdn 11
void TRUSTED_TWrapS_uDiagECC_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_FeeIf_Init 12
void TRUSTED_TWrapS_FeeIf_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_MainFunction 13
void TRUSTED_TWrapS_Fee_MainFunction(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_Read 14
void TRUSTED_TWrapS_Fee_Read(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint16 os_arg_BlockOffset;
   uint8* os_arg_DataBufferPtr;
   uint16 os_arg_Length;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Read;

#define TWrapS_Fee_Write 15
void TRUSTED_TWrapS_Fee_Write(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint8* os_arg_DataBufferPtr;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Write;

#define TWrapS_Fee_EraseImmediateBlock 16
void TRUSTED_TWrapS_Fee_EraseImmediateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_EraseImmediateBlock;

#define TWrapS_Fee_InvalidateBlock 17
void TRUSTED_TWrapS_Fee_InvalidateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_InvalidateBlock;

#define TWrapS_Fee_Cancel 18
void TRUSTED_TWrapS_Fee_Cancel(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_GetStatus 19
void TRUSTED_TWrapS_Fee_GetStatus(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetStatus;

#define TWrapS_Fee_GetJobResult 20
void TRUSTED_TWrapS_Fee_GetJobResult(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetJobResult;

#define TWrapS_TI_Fee_SuspendResumeErase 21
void TRUSTED_TWrapS_TI_Fee_SuspendResumeErase(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_arg_Command;
} osTFArgType_TWrapS_TI_Fee_SuspendResumeErase;



typedef union
{
   osTFArgType_NtWrapS_ProcessF0FF NtWrapS_ProcessF0FF_args;
   osTFArgType_TWrapS_Fee_Read TWrapS_Fee_Read_args;
   osTFArgType_TWrapS_Fee_Write TWrapS_Fee_Write_args;
   osTFArgType_TWrapS_Fee_EraseImmediateBlock TWrapS_Fee_EraseImmediateBlock_args;
   osTFArgType_TWrapS_Fee_InvalidateBlock TWrapS_Fee_InvalidateBlock_args;
   osTFArgType_TWrapS_Fee_GetStatus TWrapS_Fee_GetStatus_args;
   osTFArgType_TWrapS_Fee_GetJobResult TWrapS_Fee_GetJobResult_args;
   osTFArgType_TWrapS_TI_Fee_SuspendResumeErase TWrapS_TI_Fee_SuspendResumeErase_args;
} TrustedFunctionParameterType;

/* Non-trusted Functions */

#define NtWrapS_MtrPos_SCom_SetEOLMtrCals 0
void NONTRUSTED_NtWrapS_MtrPos_SCom_SetEOLMtrCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AstLmt_Scom_ManualTrqCmd 1
void NONTRUSTED_NtWrapS_AstLmt_Scom_ManualTrqCmd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_StaMd_SCom_EcuReset 2
void NONTRUSTED_NtWrapS_StaMd_SCom_EcuReset(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SCom_EOLNomMtrParam_Set 3
void NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCmdScl_SCom_Set 4
void NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Polarity_SCom_SetPolarity 5
void NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ClrHwTrqScale 6
void NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqScale(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ClrHwTrqTrim 7
void NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim 8
void NONTRUSTED_NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetEOLTrqStep 9
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetEOLTrqStep(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_CalGain 10
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalGain(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_CalOffset 11
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalOffset(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals 12
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetHwTrqScale 13
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqScale(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_HwTrq_SCom_SetHwTrqTrim 14
void NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp10 15
void NONTRUSTED_NtWrapS_XcpWriteAp10(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPosScom_Scom_HwPosSrvSetToZero 16
void NONTRUSTED_NtWrapS_AbsHwPosScom_Scom_HwPosSrvSetToZero(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCanc_Scom_SetCogTrqCal 17
void NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp8 18
void NONTRUSTED_NtWrapS_XcpWriteAp8(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp9 19
void NONTRUSTED_NtWrapS_XcpWriteAp9(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);



#endif /* _OS_TRUSTFCT_H_  End of File */

/* END OF C:\Sankar\Chrysler\Synergy\CL\Temp_work\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
