/* file: trustfct.c, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.06 */
/* configuration read from: C:\Users\pznywf\AppData\Local\Temp\~cfg4_301_EPS.ecuc.arxml.oil */
/* generation at  : Tue Jul 19 18:16:23 2016 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#pragma SET_DATA_SECTION(".osconst")

#pragma SET_CODE_SECTION(".oscode")

osqROM0 osqROM1 const osqROM2 TrustedFunctionType osqROM3 oskTrustedFctTab[osdNumberOfTrustedFunctions]=
{
   TRUSTED_NtWrapS_NvMProxy_Init,
   TRUSTED_NtWrapS_Rte_Start,
   TRUSTED_NtWrapS_PwmCdd_Init,
   TRUSTED_NtWrapS_Adc2_Init1,
   TRUSTED_NtWrapS_Wdg_TMS570LS3x_Init,
   TRUSTED_NtWrapS_WdgM_Init,
   TRUSTED_NtWrapS_Adc_Init,
   TRUSTED_TWrapS_XcpWriteAp0,
   TRUSTED_NtWrapS_ProcessF0FF,
   TRUSTED_NtWrapS_StaMd_Init1,
   TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn,
   TRUSTED_TWrapS_uDiagECC_RednRpdShtdn,
   TRUSTED_TWrapS_FeeIf_Init,
   TRUSTED_TWrapS_Fee_MainFunction,
   TRUSTED_TWrapS_Fee_Read,
   TRUSTED_TWrapS_Fee_Write,
   TRUSTED_TWrapS_Fee_EraseImmediateBlock,
   TRUSTED_TWrapS_Fee_InvalidateBlock,
   TRUSTED_TWrapS_Fee_Cancel,
   TRUSTED_TWrapS_Fee_GetStatus,
   TRUSTED_TWrapS_Fee_GetJobResult,
   TRUSTED_TWrapS_TI_Fee_SuspendResumeErase,
};

#ifndef OS_SUPPRESS_CALLEESTUB
#endif /* OS_SUPPRESS_CALLEESTUB */
osqROM0 osqROM1 const osqROM2 NonTrustedFunctionType osqROM3 oskNonTrustedFctTab[osdNumberOfNonTrustedFunctions]=
{
   NONTRUSTED_NtWrapS_MtrPos_SCom_SetEOLMtrCals,
   NONTRUSTED_NtWrapS_AstLmt_Scom_ManualTrqCmd,
   NONTRUSTED_NtWrapS_StaMd_SCom_EcuReset,
   NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set,
   NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set,
   NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqScale,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ClrHwTrqTrim,
   NONTRUSTED_NtWrapS_HwTrq_SCom_ManualSetHwTrqTrim,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetEOLTrqStep,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalGain,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalOffset,
   NONTRUSTED_NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqScale,
   NONTRUSTED_NtWrapS_HwTrq_SCom_SetHwTrqTrim,
   NONTRUSTED_NtWrapS_XcpWriteAp10,
   NONTRUSTED_NtWrapS_AbsHwPosScom_Scom_HwPosSrvSetToZero,
   NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal,
   NONTRUSTED_NtWrapS_XcpWriteAp8,
   NONTRUSTED_NtWrapS_XcpWriteAp9,
};

osqROM0 osqROM1 const osqROM2 ApplicationType osqROM3 oskNTFToAppl[osdNumberOfNonTrustedFunctions]=
{
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_10,
   Ap_8,
   Ap_9,
};

#pragma SET_DATA_SECTION()

#pragma SET_CODE_SECTION()


/* END OF C:\Sankar\Chrysler\Synergy\CL\Temp_work\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOs\trustfct.c */

