/* The following is only part of the header that was required at the 
 * time this component was made. 
 */
 

/*<NVM_BLOCK_ID_CFG>*/
#define Rte_NvmBlock_MtrPos_MtrPosSnsr_EOLData (2)
#define Rte_NvmBlock_MtrPosSnsrLearning_MtrSnsrLrnParam (3)
#define Rte_NvmBlock_MtrCurr_ShCurrCal (4)
#define Rte_NvmBlock_HwTrq_HwTrqScaleData (5)
#define Rte_NvmBlock_Polarity_EOLCtrlPolarity (6)
#define Rte_NvmBlock_HwTrq_HwTrqTrimData (7)
#define Rte_NvmBlock_DiagMgr_NTCStrgArray (8)
#define Rte_NvmBlock_LrnEOT_LearnedEOT (9)
#define Rte_NvmBlock_SrlComInput_SrlComWIRFltStatus_Cnt_u16 (10)
#define NVM_BLOCK_CUSTWIRSELECT (11)
#define NVM_BLOCK_NXTRWIRSELECT (12)
#define Deprecated2_NVM_BLOCK_PRTNUMBER (13)
#define NVM_BLOCK_EPSDEFEATS (14)
#define NvM_NVM_BLOCK_DEM (15)
#define Rte_NvmBlock_DigHwTrq_DigTrqScale (16)
#define Rte_NvmBlock_DigHwTrq_DigTrqTrim (17)
#define Rte_NvmBlock_StaMd_TypeHRamBuffer (18)
#define Rte_NvmBlock_ParamComp_EOLNomMtrParam (19)
#define Rte_NvmBlock_Return_EOLRtnRange (20)
#define Rte_NvmBlock_TrqCmdScl_TorqueCmdSF_Uls_f32 (21)
#define Rte_NvmBlock_LrnEOT_RackCntrPerf (22)
#define Deprecated_NvmBlock_MtrTrqLmt_EOLTrqCmdSclFac_Uls_u7p9 (23)
#define Deprecated_NVM_BLOCK_PRTNUMBER (24)
#define NVM_BLOCK_SER_CALPRGFLAG (25)
#define NVM_BLOCK_SER_VINDATA (26)
#define NVM_BLOCK_SER_SYSTEMNAME (27)
#define NVM_BLOCK_SER_REPAIRSHOPCODE (28)
#define NVM_BLOCK_SER_PROGDATE (29)
#define NVM_BLOCK_SER_SYSVERSCODEDDI (30)
#define NVM_BLOCK_SER_CUSTMEC (31)
#define NVM_BLOCK_SER_GMMANFDATA (32)
#define NVM_BLOCK_SER_MANFTRAC (33)
#define NVM_BLOCK_SER_ENDMODELPN (34)
#define NVM_BLOCK_SER_ENDMODELPNAC (35)
#define NVM_BLOCK_CMS_NXTRMEC (36)
#define NVM_BLOCK_CMS_ECUSRLNUM (37)
#define NVM_BLOCK_CMS_EPSSRLNUM (38)
#define NVM_BLOCK_CMS_ECUHWPN (39)
#define NVM_BLOCK_CMS_NXTRMANUFSCRATCHPAD (40)
#define NVM_BLOCK_CMS_IGNCNTR (41)
#define NVM_BLOCK_SER_GEARCFACTOR (42)
#define NVM_BLOCK_SER_GEARSRLNUM (43)
#define NVM_BLOCK_SER_SEED (44)
#define NVM_BLOCK_SER_KEY (45)
#define NVM_BLOCK_SER_ECUCONFIGDATA (46)
#define NVM_BLOCK_SER_DATAUNIVNUMSYSID (47)  /* Manually added this, number may not be right after the block is added -- KS */