#ifndef AP_ABSHWPOSSCOM_CFG_H
#define AP_ABSHWPOSSCOM_CFG_H

extern void Rte_Call_AbsHwPosScom_Per1_CP0_CheckpointReached(void);
extern void Rte_Call_AbsHwPosScom_Per1_CP1_CheckpointReached(void);
extern void Rte_Call_AbsHwPosScom_Per2_CP0_CheckpointReached(void);
extern void Rte_Call_AbsHwPosScom_Per2_CP1_CheckpointReached(void);
extern void Rte_Call_AbsHwPosScom_Per3_CP0_CheckpointReached(void);
extern void Rte_Call_AbsHwPosScom_Per3_CP1_CheckpointReached(void);
#endif