/* -----------------------------------------------------------------------------
  Filename:    can_cfg.h
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: DrvCan__base
               
               Configuration   : C:\ccm_wa\EPS\570\LWR\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\cmsynergy\My_ePWM_LWR\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1313 15LXMod.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2013-07-30  15:05:11
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CAN_CFG_H__)
#define __CAN_CFG_H__

#include "v_cfg.h"
#define HW_TMS470DCANCPUCANDLL_VERSION       0x0110
#define HW_TMS470DCANCPUCANDLL_RELEASE_VERSION 0x01

#define HW__BASECPUCANDLL_VERSION            0x0223
#define HW__BASECPUCANDLL_RELEASE_VERSION    0x01

#define DRVCAN__BASEDLL_VERSION              0x0321
#define DRVCAN__BASEDLL_RELEASE_VERSION      0x04

#define DRVCAN__BASERI14DLL_VERSION          0x0209
#define DRVCAN__BASERI14DLL_RELEASE_VERSION  0x01

#define DRVCAN__BASERI15DLL_VERSION          0x0104
#define DRVCAN__BASERI15DLL_RELEASE_VERSION  0x13

#define DRVCAN__BASEHLLDLL_VERSION           0x0305
#define DRVCAN__BASEHLLDLL_RELEASE_VERSION   0x02

#define DRVCAN__BASERI14HLLDLL_VERSION       0x0205
#define DRVCAN__BASERI14HLLDLL_RELEASE_VERSION 0x01

#define DRVCAN__BASERI15HLLDLL_VERSION       0x0101
#define DRVCAN__BASERI15HLLDLL_RELEASE_VERSION 0x03


#define kCanNumberOfChannels                 1
#define kCanNumberOfHwChannels               1
#define kCanNumberOfPhysChannels             1
#define C_DISABLE_MEMCOPY_SUPPORT
#define C_DISABLE_OSEK_OS
#define C_DISABLE_VARIABLE_DLC
#define C_DISABLE_DLC_FAILED_FCT
#define C_DISABLE_VARIABLE_RX_DATALEN
#define C_DISABLE_MULTI_ECU_CONFIG
#define C_DISABLE_MULTI_ECU_PHYS
#define C_DISABLE_EXTENDED_ID
#define C_DISABLE_MIXED_ID
#define C_DISABLE_RECEIVE_FCT

#define C_DISABLE_ECU_SWITCH_PASS
#define C_ENABLE_TRANSMIT_QUEUE
#define C_DISABLE_OVERRUN
#define C_DISABLE_INTCTRL_BY_APPL
#define C_DISABLE_COMMON_CAN
#define C_DISABLE_USER_CHECK
#define C_DISABLE_HARDWARE_CHECK
#define C_DISABLE_GEN_CHECK
#define C_DISABLE_INTERNAL_CHECK
#define C_DISABLE_DYN_RX_OBJECTS
#define C_DISABLE_DYN_TX_OBJECTS
#define C_DISABLE_DYN_TX_ID
#define C_DISABLE_DYN_TX_DLC
#define C_DISABLE_DYN_TX_DATAPTR
#define C_DISABLE_DYN_TX_PRETRANS_FCT
#define C_DISABLE_DYN_TX_CONF_FCT
#define C_DISABLE_EXTENDED_STATUS
#define C_DISABLE_TX_OBSERVE
#define C_DISABLE_HW_LOOP_TIMER
#define C_DISABLE_NOT_MATCHED_FCT
#define C_SECURITY_LEVEL                     30

#define C_DISABLE_MULTICHANNEL_API
#define C_ENABLE_PART_OFFLINE
#define C_DISABLE_MSG_TRANSMIT
#define C_DISABLE_MSG_TRANSMIT_CONF_FCT

#define C_ENABLE_RANGE_0
#define C_DISABLE_RANGE_1
#define C_DISABLE_RANGE_2
#define C_DISABLE_RANGE_3
#define ApplCanBusOff                        NmCanError

#define ApplCanRange0Precopy                 NmPrecopy
#define kCanNumberOfTxObjects                6
#define kCanNumberOfTxStatObjects            6
#define kCanNumberOfTxDynObjects             0
#define kCanNumberOfRxObjects                36
#define kCanNumberOfRxStatFullCANObjects     36
#define kCanNumberOfRxStatBasicCANObjects    0
#define kCanNumberOfRxDynFullCANObjects      0
#define kCanNumberOfRxDynBasicCANObjects     0
#define kCanNumberOfRxDynObjects             0
#define kCanNumberOfRxStatObjects            36
#define kCanNumberOfConfFlags                1
#define kCanNumberOfIndFlags                 1
#define kCanNumberOfConfirmationFlags        1
#define kCanNumberOfIndicationFlags          1
#define kCanNumberOfInitObjects              1
#define kCanExtNumberOfInitObjects           0
#define kCanHwRxDynFullStartIndex            62
#define C_SEARCH_LINEAR

#define C_ENABLE_RX_MSG_INDIRECTION

#define C_ENABLE_CONFIRMATION_FLAG
#define C_ENABLE_INDICATION_FLAG
#define C_DISABLE_PRETRANSMIT_FCT
#define C_ENABLE_CONFIRMATION_FCT
#define C_DISABLE_INDICATION_FCT
#define C_ENABLE_PRECOPY_FCT
#define C_ENABLE_COPY_TX_DATA
#define C_ENABLE_COPY_RX_DATA
#define C_ENABLE_DLC_CHECK
#define C_ENABLE_DLC_CHECK_MIN_DATALEN

#define C_DISABLE_GENERIC_PRECOPY

#define C_SEND_GRP_NONE                      0x00
#define C_SEND_GRP_ALL                       0xFF
#define C_SEND_GRP_APPL                      0x01
#define C_SEND_GRP_NM                        0x02
#define C_SEND_GRP_DIAG                      0x04
#define C_SEND_GRP_USER3                     0x08
#define C_SEND_GRP_USER4                     0x10
#define C_SEND_GRP_USER5                     0x20
#define C_SEND_GRP_USER6                     0x40
#define C_SEND_GRP_USER7                     0x80
#define C_DISABLE_CAN_CANCEL_NOTIFICATION

#define kCanPhysToLogChannelIndex_0
#define C_RANGE0_ACC_MASK                    0x03F

#define C_RANGE0_ACC_CODE                    0x400

#define C_ENABLE_RX_FULLCAN_OBJECTS
#define C_ENABLE_RX_BASICCAN_OBJECTS
#define kCanNumberOfRxFullCANObjects         36

#define kCanNumberOfRxBasicCANObjects        0
#define kCanNumberOfUsedRxBasicCANObjects    2

#define kCanInitObj1                         0
#define C_ENABLE_COND_RECEIVE_FCT

#define C_DISABLE_TX_MASK_EXT_ID
#define C_DISABLE_RX_MASK_EXT_ID
#define C_MASK_EXT_ID                        0xFFFFFFFF

#define C_ENABLE_CAN_CAN_INTERRUPT_CONTROL
#define C_DISABLE_CAN_TX_CONF_FCT

#define C_DISABLE_TX_POLLING
#define C_ENABLE_RX_BASICCAN_POLLING
#define C_ENABLE_RX_FULLCAN_POLLING
#define C_ENABLE_ERROR_POLLING
#define C_DISABLE_WAKEUP_POLLING
#define C_DISABLE_MULTIPLE_BASICCAN
#define C_ENABLE_FULLCAN_OVERRUN
#define C_DISABLE_OSEK_OS_INTCAT2
#define C_ENABLE_COPY_RX_DATA_WITH_DLC
#define kCanTxQueueBytes                     4
#define kCanNumberOfMaxBasicCAN              1
#define kCanNumberOfHwObjPerBasicCan         2
#define C_DISABLE_CAN_RAM_CHECK
#define C_DISABLE_SLEEP_WAKEUP
#define C_DISABLE_CANCEL_IN_HW
#define C_DISABLE_ONLINE_OFFLINE_CALLBACK_FCT

#define C_DISABLE_CAN_MSG_TRANSMIT_CANCEL_NOTIFICATION

#define C_RANGE0_IDTYPE                      kCanIdTypeStd
#define kCanChannel_Channel0                 0
#define C_DISABLE_INTCTRL_ADD_CAN_FCT
#if defined(C_SINGLE_RECEIVE_BUFFER) || defined(C_MULTIPLE_RECEIVE_BUFFER)
#error "DrvCan__baseRI1.5 doesn't support Single/Multiple Receive Buffer API for the callback 'ApplCanMsgReceived'!"
#endif

#define C_DISABLE_RETRANSMIT
#define kCanNumberOfUsedCanTxIdTables        1
#define kCanNumberOfUsedCanRxIdTables        1
#define kCanHwTxStartIndex                   0

#define kCanHwUnusedStartIndex               7

#define kCanHwRxFullStartIndex               26

#define kCanHwRxBasicStartIndex              62

#define kCanNumberOfUsedTxCANObjects         7

#define kCanNumberOfUnusedObjects            19

#define kCanNumberOfTxDirectObjects          6

#define C_ENABLE_TX_FULLCAN_OBJECTS


#define kCanHwTxNormalIndex                  6

#define C_DISABLE_RX_QUEUE
#define C_DISABLE_APPLCANPRERXQUEUE
#define C_DISABLE_RX_QUEUE_RANGE
#define C_DISABLE_RXQUEUE_OVERRUN_NOTIFY

#define C_ENABLE_INDIVIDUAL_POLLING
#define kCanNumberOfHwObjIndivPolling        64

#define kCanBasisAdr                         0xFFF7DC00
#define kCanInterruptSrc                     0x00010000
#define kCanVimClrReg                        0xFFFFFE40
#define kCanVimSetReg                        0xFFFFFE30
#define kCanNumberOfMsgObj                   64


#define C_DISABLE_DCAN_ISSUE22_WORKAROUND
#undef C_DISABLE_INTCTRL_ADD_CAN_FCT
#define C_ENABLE_INTCTRL_ADD_CAN_FCT
#include "Os.h"


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy_WorkArea\ESG_Dev_65\Chrysler_LWR_EPS_TMS570-tzj9qy\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\can_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 103168731
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __CAN_CFG_H__ */
