/* -----------------------------------------------------------------------------
  Filename:    dbk_par.c
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Il_Dbkom
               
               Configuration   : C:\ccm_wa\EPS\570\LWR\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\cmsynergy\My_ePWM_LWR\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1313 15LXMod.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2013-08-06  08:33:50
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

#include "v_inc.h"
#include "can_inc.h"
#include "dbk_par.h"


/* -----------------------------------------------------------------------------
    &&&~ Tables for tx messages
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 DbkTxMsgCanToDbkIndirection[kCanNumberOfTxObjects] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  kCanTxHandleNotUsed /* ID: 0x0000059a, Handle: 1, ECU_APPL_EPS [FC] */, 
  kCanTxHandleNotUsed /* ID: 0x000004da, Handle: 2, D_RS_EPS [FC] */, 
  kCanTxHandleNotUsed /* ID: 0x0000041a, Handle: 3, NM_EPS [BC] */, 
  1 /* ID: 0x00000220, Handle: 4, EPS_1 [FC] */, 
  2 /* ID: 0x0000012c, Handle: 5, EPS_A1 [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 DbkTxMsgDbkToCanIndirection[kDbkNumberOfTxObjects] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  4 /* ID: 0x00000220, Handle: 4, EPS_1 [FC] */, 
  5 /* ID: 0x0000012c, Handle: 5, EPS_A1 [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 t_TxMsgAttributes V_MEMROM2 DbkTxMsgAttributes[kDbkNumberOfTxObjects] = 
{
  { 0, 0, 1, 1, 0, 0, 0 }, 
  { 1, 1, 0, 1, 0, 0, 0 }, 
  { 1, 1, 0, 0, 0, 0, 0 }
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbkSignalStateType V_MEMROM2 DbkTxMsgSignalStateOffset[kDbkNumberOfTxObjects + 1] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  0 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  0 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */, 
  0
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkTxMsgTimer1[kDbkNumberOfTxObjects] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  3 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  1 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkTxMsgTimer2[kDbkNumberOfTxObjects] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  6 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  51 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxMsgDeltaT[kDbkNumberOfTxObjects] = 
{
  10 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  10 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  10 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxMsgNRepeat[kDbkNumberOfTxObjects] = 
{
  2 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  2 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  2 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbkSigHandleType V_MEMROM2 DbkTxMsgDataOffset[kDbkNumberOfTxObjects+1] = 
{
  0 /* ID: 0x0000061a, Handle: 0, SD_RS_EPS [FC] */, 
  1 /* ID: 0x00000220, Handle: 1, EPS_1 [FC] */, 
  2 /* ID: 0x0000012c, Handle: 2, EPS_A1 [FC] */, 
  3
};
/* ROM CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Tables for tx signals
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbkTxOffsetType V_MEMROM2 DbkTxSigOffset[kDbkNumberOfTxSignals] = 
{
  0 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  8 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  16 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkTxSigMask[kDbkNumberOfTxSignals] = 
{
  0x0008 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0x0008 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbknByteOffsetType V_MEMROM2 DbkTxSigStartbit[kDbkNumberOfTxSignals] = 
{
  0 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  8 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  16 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 DbkTxSigMessageHdl[kDbkNumberOfTxSignals] = 
{
  0, 
  1, 
  2
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkTxSigX1[kDbkNumberOfTxSignals] = 
{
  0x0000 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0x0000 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkTxSigX2[kDbkNumberOfTxSignals] = 
{
  0x0000 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0x0000 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_TX_CONF_FLAG
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxSigConfirmationOffset[kDbkNumberOfTxSignals] = 
{
  0 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxSigConfirmationMask[kDbkNumberOfTxSignals] = 
{
  0x01 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0x02 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_TX_CONF_FUNC
V_MEMROM0 V_MEMROM1 ConfirmationFuncPtr V_MEMROM2 DbkTxSigConfirmationFunc[kDbkNumberOfTxSignals] = 
{
  FrfmRoelConfirmation /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  EPS1_PKTConfirmation /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbkSignalStateType V_MEMROM2 DbkTxSigSignalStateOffset[kDbkNumberOfTxSignals] = 
{
  0 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxSigSignalStateMask[kDbkNumberOfTxSignals] = 
{
  0x00 /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0x00 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 t_TxSigSwitch V_MEMROM2 DbkTxSigSwitch[kDbkNumberOfTxSignals] = 
{
  { 6, 1, 0, 1, 1, 0 } /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  { 6, 1, 0, 0, 1, 0 } /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 1, 0, 0, 0, 0 } /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkTxSignByteMask[kDbkNumberOfTxXxBytes] = 
{
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    0,Name:                      SD_RS_EPS,Size: 64,Type:  nByte,no Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xE7 /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                      EPS_1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFE /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFC /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                     EPS_A1_PKT,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Tables for rx messages
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 t_RxMsgAttributes V_MEMROM2 DbkRxMsgAttributes[kDbkNumberOfRxObjects] = 
{
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }, 
  { 0, 1, 1, 0 }
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkRxMsgDeltaT[kDbkNumberOfRxObjects] = 
{
  2100 /* ID: 0x0000044a, Handle: 0, VehCfg5 [FC] */, 
  2100 /* ID: 0x000003f5, Handle: 1, EcuCfg6 [FC] */, 
  0 /* ID: 0x000003eb, Handle: 2, VehCfg4 [FC] */, 
  2100 /* ID: 0x000003ea, Handle: 3, VehCfg3 [FC] */, 
  2100 /* ID: 0x000003e9, Handle: 4, VehCfg2 [FC] */, 
  525 /* ID: 0x000003e8, Handle: 5, VehCfg1 [FC] */, 
  2100 /* ID: 0x000003e4, Handle: 6, NET_CFG_PT [FC] */, 
  105 /* ID: 0x000003e1, Handle: 7, ENG_CFG [FC] */, 
  105 /* ID: 0x000003e0, Handle: 8, VIN [FC] */, 
  0 /* ID: 0x00000381, Handle: 9, VehCfg7 [FC] */, 
  0 /* ID: 0x00000334, Handle: 10, CBC_PT1 [FC] */, 
  1050 /* ID: 0x0000031f, Handle: 11, GW_LIN_I_C2 [FC] */, 
  0 /* ID: 0x00000316, Handle: 12, CFG_RQ_C [FC] */, 
  0 /* ID: 0x00000314, Handle: 13, CFG_RQ [FC] */, 
  1050 /* ID: 0x00000310, Handle: 14, IC_A1 [FC] */, 
  0 /* ID: 0x00000302, Handle: 15, EPB_1 [FC] */, 
  0 /* ID: 0x000002f8, Handle: 16, ECM_A3 [FC] */, 
  0 /* ID: 0x000002a0, Handle: 17, ECM_INDICATORS [FC] */, 
  0 /* ID: 0x0000029f, Handle: 18, PTS_StrCtrl [FC] */, 
  0 /* ID: 0x00000294, Handle: 19, DST_TOC [FC] */, 
  0 /* ID: 0x00000292, Handle: 20, HALF_MTO_SteerControl [FC] */, 
  11 /* ID: 0x00000202, Handle: 21, WHEEL_SPEED_2 [FC] */, 
  105 /* ID: 0x00000200, Handle: 22, CBC_PT3 [FC] */, 
  0 /* ID: 0x00000170, Handle: 23, TRNS_STAT [FC] */, 
  0 /* ID: 0x00000158, Handle: 24, ESP_A6 [FC] */, 
  0 /* ID: 0x0000014c, Handle: 25, ESP_A4 [FC] */, 
  0 /* ID: 0x00000144, Handle: 26, TRNS_SPD [FC] */, 
  0 /* ID: 0x00000126, Handle: 27, ORC_YRS_DATA [FC] */, 
  0 /* ID: 0x00000124, Handle: 28, ESP_A5 [FC] */, 
  21 /* ID: 0x0000011c, Handle: 29, ESP_A8 [FC] */, 
  21 /* ID: 0x00000112, Handle: 30, CBC_PT2 [FC] */, 
  11 /* ID: 0x00000108, Handle: 31, ECM_A1 [FC] */, 
  11 /* ID: 0x00000102, Handle: 32, SCCM_STW_ANGL_STAT [FC] */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 DbkSigHandleType V_MEMROM2 DbkRxMsgDataOffset[kDbkNumberOfRxObjects+1] = 
{
  0 /* ID: 0x0000044a, Handle: 0, VehCfg5 [FC] */, 
  1 /* ID: 0x000003f5, Handle: 1, EcuCfg6 [FC] */, 
  3 /* ID: 0x000003eb, Handle: 2, VehCfg4 [FC] */, 
  4 /* ID: 0x000003ea, Handle: 3, VehCfg3 [FC] */, 
  5 /* ID: 0x000003e9, Handle: 4, VehCfg2 [FC] */, 
  6 /* ID: 0x000003e8, Handle: 5, VehCfg1 [FC] */, 
  7 /* ID: 0x000003e4, Handle: 6, NET_CFG_PT [FC] */, 
  8 /* ID: 0x000003e1, Handle: 7, ENG_CFG [FC] */, 
  9 /* ID: 0x000003e0, Handle: 8, VIN [FC] */, 
  10 /* ID: 0x00000381, Handle: 9, VehCfg7 [FC] */, 
  11 /* ID: 0x00000334, Handle: 10, CBC_PT1 [FC] */, 
  12 /* ID: 0x0000031f, Handle: 11, GW_LIN_I_C2 [FC] */, 
  13 /* ID: 0x00000316, Handle: 12, CFG_RQ_C [FC] */, 
  14 /* ID: 0x00000314, Handle: 13, CFG_RQ [FC] */, 
  15 /* ID: 0x00000310, Handle: 14, IC_A1 [FC] */, 
  16 /* ID: 0x00000302, Handle: 15, EPB_1 [FC] */, 
  17 /* ID: 0x000002f8, Handle: 16, ECM_A3 [FC] */, 
  18 /* ID: 0x000002a0, Handle: 17, ECM_INDICATORS [FC] */, 
  19 /* ID: 0x0000029f, Handle: 18, PTS_StrCtrl [FC] */, 
  20 /* ID: 0x00000294, Handle: 19, DST_TOC [FC] */, 
  21 /* ID: 0x00000292, Handle: 20, HALF_MTO_SteerControl [FC] */, 
  22 /* ID: 0x00000202, Handle: 21, WHEEL_SPEED_2 [FC] */, 
  23 /* ID: 0x00000200, Handle: 22, CBC_PT3 [FC] */, 
  26 /* ID: 0x00000170, Handle: 23, TRNS_STAT [FC] */, 
  27 /* ID: 0x00000158, Handle: 24, ESP_A6 [FC] */, 
  28 /* ID: 0x0000014c, Handle: 25, ESP_A4 [FC] */, 
  30 /* ID: 0x00000144, Handle: 26, TRNS_SPD [FC] */, 
  31 /* ID: 0x00000126, Handle: 27, ORC_YRS_DATA [FC] */, 
  32 /* ID: 0x00000124, Handle: 28, ESP_A5 [FC] */, 
  33 /* ID: 0x0000011c, Handle: 29, ESP_A8 [FC] */, 
  34 /* ID: 0x00000112, Handle: 30, CBC_PT2 [FC] */, 
  35 /* ID: 0x00000108, Handle: 31, ECM_A1 [FC] */, 
  36 /* ID: 0x00000102, Handle: 32, SCCM_STW_ANGL_STAT [FC] */, 
  37
};
/* ROM CATEGORY 2 END */



/* -----------------------------------------------------------------------------
    &&&~ Tables for rx signals
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbkRxOffsetType V_MEMROM2 DbkRxSigOffset[kDbkNumberOfRxSignals] = 
{
  24 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  32 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  34 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  40 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  48 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  56 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  64 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  72 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  80 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  87 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  95 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  103 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  117 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  119 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  122 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  129 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  133 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  141 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  152 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  157 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  165 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  173 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  179 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  187 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  188 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  193 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  195 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  203 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  215 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  216 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  220 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  227 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  235 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  243 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  251 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  253 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  261 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigBytePos[kDbkNumberOfRxSignals] = 
{
  0 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  2 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  6 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  4 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  3 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  1 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  6 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  4 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  5 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  1 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 2 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkRxSigMask[kDbkNumberOfRxSignals] = 
{
  0x0008 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0003 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0xFFFF /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0x0008 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x0004 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x0008 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0010 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0x0007 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0x0003 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x0003 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x0003 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x0008 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00FF /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0x0008 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x0006 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x0004 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0x00FF /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0xFFFF /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0x00FF /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0x0008 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x00FF /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0x00FF /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0x0F00 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0x0008 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0004 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0x0008 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0700 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0x0008 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0008 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 DbknByteOffsetType V_MEMROM2 DbkRxSigStartbit[kDbkNumberOfRxSignals] = 
{
  0 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  8 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  16 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  24 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  32 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  40 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  48 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  52 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  60 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  4 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  68 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  71 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  74 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  82 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  90 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  98 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  106 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  114 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  74 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  120 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  128 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  136 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  74 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  144 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  152 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  160 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkRxSigX1[kDbkNumberOfRxSignals] = 
{
  0x0000 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0x0000 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0x0000 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0x0000 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0x0000 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x0000 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x0000 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x0000 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x0000 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0x0000 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0x0000 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0x0000 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 DbkRxSigX2[kDbkNumberOfRxSignals] = 
{
  0x0000 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0x0000 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0x0000 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0x0000 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0x0000 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x0000 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x0000 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x0000 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x0000 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0x0000 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0x0000 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0x0000 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0x0000 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0x0000 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0000 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_RX_IND_FLAG
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigIndicationOffset[kDbkNumberOfRxSignals] = 
{
  0 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  1 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  1 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  1 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  1 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  1 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  1 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  1 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  1 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  2 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  2 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  2 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  2 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  2 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  2 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  2 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  2 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  3 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  3 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  3 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  3 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  3 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  3 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  3 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  3 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  4 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  4 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  4 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  4 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  4 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigIndicationMask[kDbkNumberOfRxSignals] = 
{
  0x01 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x02 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0x04 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0x08 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x10 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x20 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x40 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x80 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x01 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x02 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x04 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x08 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0x10 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0x20 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x40 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x80 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x01 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x02 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x04 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0x08 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x10 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x20 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x40 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0x80 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0x01 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0x02 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0x04 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x08 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x10 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0x20 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0x40 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0x80 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x01 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0x02 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x04 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0x08 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x10 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_RX_IND_FUNC
V_MEMROM0 V_MEMROM1 IndicationFuncPtr V_MEMROM2 DbkRxSigIndicationFunc[kDbkNumberOfRxSignals] = 
{
  V_NULL /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  V_NULL /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  V_NULL /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  V_NULL /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  V_NULL /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  V_NULL /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  V_NULL /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  V_NULL /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  V_NULL /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  V_NULL /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  V_NULL /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  V_NULL /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_RX_TIMEOUT_FLAG
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigTimeoutOffset[kDbkNumberOfRxSignals] = 
{
  0 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigTimeoutMask[kDbkNumberOfRxSignals] = 
{
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  0x00 /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x00 /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  0x00 /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  0x00 /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x00 /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x00 /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x00 /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  0x00 /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x00 /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  0x00 /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  0x00 /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  0x00 /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  0x00 /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  0x00 /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  0x00 /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  0x00 /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  0x00 /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  0x00 /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
#ifdef DBK_ENABLE_RX_TIMEOUT_FUNC
V_MEMROM0 V_MEMROM1 TimeoutFuncPtr V_MEMROM2 DbkRxSigTimeoutFunc[kDbkNumberOfRxSignals] = 
{
  V_NULL /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  V_NULL /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  V_NULL /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  V_NULL /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  V_NULL /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  V_NULL /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  V_NULL /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  V_NULL /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  V_NULL /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  V_NULL /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  V_NULL /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  V_NULL /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  V_NULL /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  V_NULL /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  V_NULL /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};

#endif

/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSignByteMask[kDbkNumberOfRxXxBytes] = 
{
  0x03 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x40 /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xC0 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    1,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x03 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x7F /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    2,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x03 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x06 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    3,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x1F /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xF3 /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    4,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x83 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x92 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x90 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x82 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    5,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    6,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x10 /* Handle:    6,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x00 /* Handle:    6,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x10 /* Handle:    6,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  0x03 /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    7,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  0x24 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:    8,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:    9,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0x03 /* Handle:    9,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0xFF /* Handle:    9,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  0xFF /* Handle:   10,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0x03 /* Handle:   10,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0xFF /* Handle:   10,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0xFF /* Handle:   11,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  0x01 /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xCB /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x7F /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xF0 /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xF0 /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   12,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0F /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   13,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  0x7F /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0xE0 /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0xF0 /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   14,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  0xF7 /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0x03 /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xE3 /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   15,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0xFF /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x00 /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x00 /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0xF0 /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0xFF /* Handle:   16,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  0x1C /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   17,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  0x3F /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x3F /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   18,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x0F /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   19,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0xF0 /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   20,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   21,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  0x3F /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0x3F /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0xFF /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0x0F /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */, 
  0x00 /* Handle:   22,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 t_RxSigSwitch V_MEMROM2 DbkRxSigSwitch[kDbkNumberOfRxSignals] = 
{
  { 6, 0, 1, 0, 0, 0 } /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  { 6, 0, 1, 0, 0, 1 } /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  { 6, 0, 1, 0, 0, 0 } /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkRxSigType[kDbkNumberOfRxSignals] = 
{
  TYP_NBYTE /* Handle:    0,Name:                    VehCfg5_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBIT /* Handle:    1,Name:                EC_ECUCfg6_Stat,Size:  2,Type:   nBit,no Container */, 
  TYP_WORD /* Handle:    2,Name:                    EC_Steering,Size: 16,Type:   Word,no Container */, 
  TYP_NBYTE /* Handle:    3,Name:                    VehCfg4_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    4,Name:                    VehCfg3_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    5,Name:                    VehCfg2_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    6,Name:                    VehCfg1_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    7,Name:                NET_CFG_DATA_PT,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    8,Name:                        ENG_CFG,Size: 32,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:    9,Name:                       VIN_INFO,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   10,Name:                    VehCfg7_Pkt,Size: 64,Type:  nByte,is Container */, 
  TYP_NBIT /* Handle:   11,Name:                       REV_GEAR,Size:  1,Type:   nBit,no Container */, 
  TYP_NBIT /* Handle:   12,Name:                   EPS_MODE_REQ,Size:  3,Type:   nBit,no Container */, 
  TYP_NBYTE /* Handle:   13,Name:                       CFG_RQ_C,Size: 24,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   14,Name:                         CFG_RQ,Size: 24,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   15,Name:                            ODO,Size: 24,Type:  nByte,no Container */, 
  TYP_NBYTE /* Handle:   16,Name:                          EPB_1,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   17,Name:                     ECM_A3_PKT,Size: 64,Type:  nByte,is Container */, 
  TYP_BYTE /* Handle:   18,Name:                     EngOilTemp,Size:  8,Type:   Byte,no Container */, 
  TYP_NBYTE /* Handle:   19,Name:                    PTS_StrCtrl,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   20,Name:                        DST_TOC,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   21,Name:                   HaLF_StrCtrl,Size: 48,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   22,Name:                   WHEEL_SPEED2,Size: 32,Type:  nByte,is Container */, 
  TYP_BYTE /* Handle:   23,Name:                  AirTemp_Outsd,Size:  8,Type:   Byte,no Container */, 
  TYP_WORD /* Handle:   24,Name:                   AMB_TEMP_AVG,Size: 16,Type:   Word,no Container */, 
  TYP_BYTE /* Handle:   25,Name:                      BATT_VOLT,Size:  8,Type:   Byte,no Container */, 
  TYP_NBYTE /* Handle:   26,Name:                  TRNS_STAT_PKT,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   27,Name:                    WHEEL_SPEED,Size: 64,Type:  nByte,is Container */, 
  TYP_BYTE /* Handle:   28,Name:                     VehAccel_X,Size:  8,Type:   Byte,no Container */, 
  TYP_BYTE /* Handle:   29,Name:                     VehAccel_Y,Size:  8,Type:   Byte,no Container */, 
  TYP_WORD /* Handle:   30,Name:                       Gear_Pkt,Size: 16,Type:   Word,is Container */, 
  TYP_NBYTE /* Handle:   31,Name:                    ORC_YRS_PKT,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   32,Name:                   ESP_WHL_PULS,Size: 32,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   33,Name:                  VEH_SPEED_PKT,Size: 64,Type:  nByte,is Container */, 
  TYP_WORD /* Handle:   34,Name:                   VehStart_PKT,Size: 16,Type:   Word,is Container */, 
  TYP_NBYTE /* Handle:   35,Name:                     ECM_A1_PKT,Size: 64,Type:  nByte,is Container */, 
  TYP_NBYTE /* Handle:   36,Name:                         LRW_ST,Size: 64,Type:  nByte,is Container */
};
/* ROM CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Tables for messages
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 3 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 DbkMsgDefault[kDbkNumberOfBytesEx] = 
{
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x07, 0xFF, 0x0F, 0xFF, 0x1C, 0x00, 0x00, 0xFF, 
  0x02, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0xC3, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 
  0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0x03, 0x70, 0xFF, 0x03, 0x7F, 0xFF, 0x00, 0x00, 
  0x03, 0x00, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFF, 0x7F, 0xF0, 0xFF, 0x0F, 0xFF, 0x00, 
  0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0xFF, 0xEF, 0xE7, 0xE7, 0xE7, 0x1F, 0x00, 
  0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x03, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x60, 0x00, 0x00, 0x3F, 0xFF, 0xFC, 0x00, 0x00, 
  0x07, 0xFF, 0x07, 0xFF, 0x00, 0x00, 0x00, 0x04, 
  0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 
  0x01, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x07, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 
  0x1F, 0xFF, 0x1F, 0xFF, 0x00, 0xFF, 0x0F, 0xFF, 
  0x60, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x07, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 
  0x00, 0x00, 0x00, 0x00, 0xC0, 0x00, 0x00, 0xFF, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0x1C, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 
  0x00, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x0F, 0xFF, 0x00, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF, 
  0x0F, 0xFF, 0x0F, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 
  0x00, 0x00, 
  0xFF, 0xFF, 0x1F, 0xFF, 0x1F, 0xFF, 0x00, 0xFF, 
  0x3F, 0xFF, 0x3F, 0xFF, 0x03, 0x00, 0x00, 0xFF
};
/* ROM CATEGORY 3 END */





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy_WorkArea\ESG_Dev_65\Chrysler_LWR_EPS_TMS570-tzj9qy\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dbk_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <C:\Synergy_WorkArea\ESG_Dev_65\Chrysler_LWR_EPS_TMS570-tzj9qy\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dbk_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

