/* -----------------------------------------------------------------------------
  Filename:    dbk_cfg.h
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Il_Dbkom
               
               Configuration   : C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1232 EPS.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2013-04-25  11:29:38
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DBK_CFG_H__)
#define __DBK_CFG_H__

#ifndef DBK_INIT
#define DBK_INIT
#endif

/* -----------------------------------------------------------------------------
    &&&~ Generation defines
 ----------------------------------------------------------------------------- */

#define DBK_VERSION_REF_IMPLEMENTATION       0x0220
#define GENDATE                              0x0522
#define GENTIME                              0x1611
#define DBK_ENABLE_FAST_RAM
#define DBK_DISABLE_DWORD_SUPPORT


/* -----------------------------------------------------------------------------
    &&&~ Channel parameter
 ----------------------------------------------------------------------------- */

#define kDbkNumberOfChannels                 1


/* -----------------------------------------------------------------------------
    &&&~ Controller defines
 ----------------------------------------------------------------------------- */

#define CONTROLLER_TYPE                      112
#define DERIVATE_TYPE                        2


/* -----------------------------------------------------------------------------
    &&&~ Number defines
 ----------------------------------------------------------------------------- */

#define kDbkNumberOfTxObjects                3
#define kDbkNumberOfRxObjects                33
#define kDbkNumberOfBytesEx                  269
#define kDbkNumberOfRxSignals                37
#define kDbkNumberOfTotalTxSignals           3
#define kDbkNumberOfTxSignals                3
#define kDbkNumberOfTxSigStateBytes          0
#define kDbkNumberOfConfFlags                2
#define kDbkNumberOfTOFlags                  0
#define kDbkNumberOfIndFlags                 37
#define kDbkNumberOfTxXxBytes                24
#define kDbkNumberOfTxXxX1Bytes              0
#define kDbkNumberOfTxXxX2Bytes              0
#define kDbkNumberOfRxXxBytes                168
#define kDbkNumberOfRxXxX1Bytes              0
#define kDbkNumberOfRxXxX2Bytes              0


/* -----------------------------------------------------------------------------
    &&&~ Flag defines
 ----------------------------------------------------------------------------- */

#define DBK_DISABLE_TX_CHANNEL_SPECIFIC
#define DBK_ENABLE_TX_CONF_FUNC
#define DBK_ENABLE_TX_CONF_FLAG
#define DBK_ENABLE_RX_IND_FLAG
#define DBK_DISABLE_RX_IND_FUNC
#define DBK_DISABLE_RX_TIMEOUT_FUNC
#define DBK_DISABLE_RX_TIMEOUT_FLAG


/* -----------------------------------------------------------------------------
    &&&~ StmSignalType defines
 ----------------------------------------------------------------------------- */

#define _NBIT_SIGNALE_AKTIV
#define _BYTE_SIGNALE_AKTIV
#define _WORD_SIGNALE_AKTIV
#define _NBYTE_SIGNALE_AKTIV
#define _NBYTE_TX_SIGNALE_AKTIV
#define _NBIT_RX_SIGNALE_AKTIV
#define _BYTE_RX_SIGNALE_AKTIV
#define _WORD_RX_SIGNALE_AKTIV
#define _NBYTE_RX_SIGNALE_AKTIV
#define _NBIT_BYTE_RX_SIGNALE_AKTIV
#define _N16BIT_WORD_RX_SIGNALE_AKTIV
#define DBK_DISABLE_SENDTYPE_FAST


/* -----------------------------------------------------------------------------
    &&&~ Signal evaluators
 ----------------------------------------------------------------------------- */

#define NBYTE_TX_EVALMODE_6_USED
#define NBIT_RX_EVALMODE_6_USED
#define BYTE_RX_EVALMODE_6_USED
#define WORD_RX_EVALMODE_6_USED
#define NBYTE_RX_EVALMODE_6_USED
#define DBK_ENABLE_RX_SIGNALEVAL_ALWAYSTRUE


/* -----------------------------------------------------------------------------
    &&&~ Multiple ECU define
 ----------------------------------------------------------------------------- */

#define DBK_DISABLE_MULTIPLE_ECU
#define kDbkNumberOfNodes                    1


/* -----------------------------------------------------------------------------
    &&&~ Production define
 ----------------------------------------------------------------------------- */

/* Insert defines here; #ifdef C_ENABLE_PRODUCTION */


/* -----------------------------------------------------------------------------
    &&&~ Container define
 ----------------------------------------------------------------------------- */

#define TX_CONTAINER_GAPS_NBYTE
#define RX_CONTAINER_GAPS_WORD
#define RX_CONTAINER_GAPS_NBYTE


/* -----------------------------------------------------------------------------
    &&&~ Signal define
 ----------------------------------------------------------------------------- */

#define DBK_DISABLE_DEFAULT_TO


/* -----------------------------------------------------------------------------
    &&&~ Conversion defines
 ----------------------------------------------------------------------------- */

#define DBK_ENABLE_TX_NEVER_BYTESWAP
#define DBK_ENABLE_RX_NEVER_BYTESWAP
#define DBK_DISABLE_TX_GENERAL_BYTESWAP
#define DBK_DISABLE_RX_GENERAL_BYTESWAP


#define DBKCHANNEL

/* -----------------------------------------------------------------------------
    &&&~ OptimizeTxPut
 ----------------------------------------------------------------------------- */

#define DBK_DISABLE_OPTIMIZE_TX_PUT




/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy_WorkArea\ESG_Dev_65\Chrysler_LWR_EPS_TMS570-tzj9qy\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dbk_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 103168731
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DBK_CFG_H__ */
