/* -----------------------------------------------------------------------------
  Filename:    dpm_cfg.h
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: DPM
               
               Configuration   : C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\Documents and Settings\sz1dx6\My Documents\Synergy\ccm_wa\sz1dx6\Chysler\01.00.09\sz1dx6\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1232 EPS.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2012-12-10  17:17:38
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DPM_CFG_H__)
#define __DPM_CFG_H__

#define DPM_DLLDLL_VERSION                   0x0205
#define DPM_DLLDLL_RELEASE_VERSION           0x43
#define C_ENABLE_DPM 

#define DPM_DISABLE_REST_IND_FUNC 

#define DPM_DISABLE_USER_NOTIFICATION

#define DPM_DISABLE_EXTENDEND_INITIALIZATION

#define DPM_USER_BYTE 1  /* DPM used User bytes */
#define DPM_USER_COUNT 2  /* count of users */

#define T_MINIMUM_LOCAL_MODE_DURATION  74
#define DPM_TASK_CYCLE  20
#define T_STARTUP_SLEEP_DELAY  250
  /* startup sleep delay time */

#define C_ENABLE_DPM_PRODUCTION
#define DPM_DISABLE_DEBUG

#define kDpmNumberOfChannels 1
#define DPM_SYS_USER1_CH0  0
#define DPM_EPS  1



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dpm_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 114466473
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DPM_CFG_H__ */
