/* -----------------------------------------------------------------------------
  Filename:    dpm_par.c
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: DPM
               
               Configuration   : C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\Documents and Settings\sz1dx6\My Documents\Synergy\ccm_wa\sz1dx6\Chysler\01.00.09\sz1dx6\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1232 EPS.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2012-12-10  17:17:38
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define DPM_PAR_MODULE

#include "ccl_inc.h"
#include "dbk_par.h"
#include "dpm_par.h"


V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cDpmUserByteTable[2] = {
  0x0, 0x0
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cDpmUserSetMask[2] = {
  0x1, 0x2
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cDpmUserClearMask[2] = {
  0xfe, 0xfd
};
/* *** DPM external Request functions *** */
void DPM_API_CALL_TYPE DpmExternalRequest(t_DpmUserNumber UserNumber)
{
    gDpmUserExternalRequest[cDpmUserByteTable[UserNumber]] |= cDpmUserSetMask[UserNumber];
    gDpmUserLocalRequest[cDpmUserByteTable[UserNumber]] &= cDpmUserClearMask[UserNumber];

  switch(UserNumber)
  {
    case 0x0:
      CclSet_Sys_User1_CH0();
      break;

    case 0x1:
      CclSet_DPM_EPS();
      break;

    default:
      DPM_ASSERT(0, DPM_ERR_INVALID_USER_NO);
      break;

  }
}

  /* *** DPM Local Request functions *** */
void DPM_API_CALL_TYPE DpmLocalRequest(t_DpmUserNumber UserNumber)
{
    gDpmUserExternalRequest[cDpmUserByteTable[UserNumber]] &= cDpmUserClearMask[UserNumber];
    gDpmUserLocalRequest[cDpmUserByteTable[UserNumber]] |= cDpmUserSetMask[UserNumber];

  switch(UserNumber)
  {
    case 0x0:
      CclRel_Sys_User1_CH0();
      break;

    case 0x1:
      CclRel_DPM_EPS();
      break;

    default:
      DPM_ASSERT(0, DPM_ERR_INVALID_USER_NO);
      break;

  }
}

  /* *** DPM Sleep Request functions *** */
void DPM_API_CALL_TYPE DpmSleepRequest(t_DpmUserNumber UserNumber)
{
    gDpmUserExternalRequest[cDpmUserByteTable[UserNumber]] &= cDpmUserClearMask[UserNumber];
    gDpmUserLocalRequest[cDpmUserByteTable[UserNumber]] &= cDpmUserClearMask[UserNumber];

  switch(UserNumber)
  {
    case 0x0:
      CclRel_Sys_User1_CH0();
      break;

    case 0x1:
      CclRel_DPM_EPS();
      break;

    default:
      DPM_ASSERT(0, DPM_ERR_INVALID_USER_NO);
      break;

  }
}



/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dpm_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\dpm_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

