/* -----------------------------------------------------------------------------
  Filename:    drv_par.h
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyDriverBase
               
               Configuration   : C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1232 EPS.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2013-04-25  11:29:38
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DRV_PAR_H__)
#define __DRV_PAR_H__

/* -----------------------------------------------------------------------------
    &&&~ Signal Structures
 ----------------------------------------------------------------------------- */

typedef struct _c_D_RS_EPS_msgTypeTag
{
  vbittype D_RS_EPS_7 : 8;
  vbittype D_RS_EPS_6 : 8;
  vbittype D_RS_EPS_5 : 8;
  vbittype D_RS_EPS_4 : 8;
  vbittype D_RS_EPS_3 : 8;
  vbittype D_RS_EPS_2 : 8;
  vbittype D_RS_EPS_1 : 8;
  vbittype D_RS_EPS_0 : 8;
} _c_D_RS_EPS_msgType;
typedef struct _c_ECU_APPL_EPS_msgTypeTag
{
  vbittype ECU_APPL_EPS_7 : 8;
  vbittype ECU_APPL_EPS_6 : 8;
  vbittype ECU_APPL_EPS_5 : 8;
  vbittype ECU_APPL_EPS_4 : 8;
  vbittype ECU_APPL_EPS_3 : 8;
  vbittype ECU_APPL_EPS_2 : 8;
  vbittype ECU_APPL_EPS_1 : 8;
  vbittype ECU_APPL_EPS_0 : 8;
} _c_ECU_APPL_EPS_msgType;
typedef struct _c_APPL_ECU_EPS_msgTypeTag
{
  vbittype APPL_ECU_EPS_7 : 8;
  vbittype APPL_ECU_EPS_6 : 8;
  vbittype APPL_ECU_EPS_5 : 8;
  vbittype APPL_ECU_EPS_4 : 8;
  vbittype APPL_ECU_EPS_3 : 8;
  vbittype APPL_ECU_EPS_2 : 8;
  vbittype APPL_ECU_EPS_1 : 8;
  vbittype APPL_ECU_EPS_0 : 8;
} _c_APPL_ECU_EPS_msgType;


/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */

#define kLRW_SNA                             16383
#define kVLRW_SNA                            16383


#define kEngRPM_SNA                          65535


#define kCmdIgnStat_SNA                      7
#define kCmdIgnStat_IGN_START                5
#define kCmdIgnStat_IGN_RUN                  4
#define kCmdIgnStat_IGN_OFF_ACC              3
#define kCmdIgnStat_IGN_ACC                  2
#define kCmdIgnStat_IGN_OFF                  1
#define kCmdIgnStat_IGN_LK                   0


#define kVEH_SPEED_SNA                       65535


#define kWhlPlsCnt_FL_SNA                    255
#define kWhlPlsCnt_FR_SNA                    255
#define kWhlPlsCnt_RL_SNA                    255
#define kWhlPlsCnt_RR_SNA                    255


#define kEPS_AsstStat_SNA                    7
#define kEPS_AsstStat_AST_RT                 2
#define kEPS_AsstStat_AST_OFF                1
#define kEPS_AsstStat_AST_ACT                0
#define kEPS_Warn_Disp_Rq_SNA                7
#define kEPS_Warn_Disp_Rq_SERV_HI            3
#define kEPS_Warn_Disp_Rq_ERR2               2
#define kEPS_Warn_Disp_Rq_ERR                1
#define kEPS_Warn_Disp_Rq_OK                 0
#define kEPS_MODE_CFG_STAT_SNA               7
#define kEPS_MODE_CFG_STAT_LAST              3
#define kEPS_MODE_CFG_STAT_MODE_3            2
#define kEPS_MODE_CFG_STAT_MODE_2            1
#define kEPS_MODE_CFG_STAT_MODE_1            0
#define kEPS_MODE_STAT_SNA                   7
#define kEPS_MODE_STAT_LAST                  3
#define kEPS_MODE_STAT_MODE_3                2
#define kEPS_MODE_STAT_MODE_2                1
#define kEPS_MODE_STAT_MODE_1                0
#define kEPS_Curr_SNA                        255


#define kVehAccel_X_SNA                      255

#define kVehAccel_Y_SNA                      255


#define kWhlRPM_FL_SNA                       16383
#define kWhlRPM_FR_SNA                       16383
#define kWhlRPM_RL_SNA                       16383
#define kWhlDir_RL_Stat_SNA                  3
#define kWhlDir_RL_Stat_BACKWARD             2
#define kWhlDir_RL_Stat_FORWARD              1
#define kWhlDir_RL_Stat_VOID                 0
#define kWhlRPM_RR_SNA                       16383
#define kWhlDir_RR_Stat_SNA                  3
#define kWhlDir_RR_Stat_BACKWARD             2
#define kWhlDir_RR_Stat_FORWARD              1
#define kWhlDir_RR_Stat_VOID                 0


#define kPRND_STAT_SNA                       7
#define kPRND_STAT_NOT_R                     5
#define kPRND_STAT_LVR_D                     4
#define kPRND_STAT_LVR_N                     2
#define kPRND_STAT_LVR_R                     1
#define kPRND_STAT_LVR_P                     0


#define kAirTemp_Outsd_SNA                   255

#define kAMB_TEMP_AVG_SNA                    65535

#define kBATT_VOLT_SNA                       255


#define kMTO_HALFDriveStyleSts_SNA           7
#define kMTO_HALFDriveStyleSts_TRACPLUS      5
#define kMTO_HALFDriveStyleSts_SPORT_PLUS    4
#define kMTO_HALFDriveStyleSts_WINTER        3
#define kMTO_HALFDriveStyleSts_SPORT         2
#define kMTO_HALFDriveStyleSts_CITY          1
#define kMTO_HALFDriveStyleSts_NORMAL        0


#define kTOC_Fault_SNA                       3
#define kTOC_Fault_FAULT                     1
#define kTOC_Fault_AVAIL                     0
#define kTOC_Act_Req_SNA                     3
#define kTOC_Act_Req_ACTIVE                  1
#define kTOC_Act_Req_NOT                     0
#define kSyncPos_SNA                         7
#define kSyncPos_NS                          4
#define kSyncPos_TEMP                        3
#define kSyncPos_PRESS                       2
#define kSyncPos_HIGH                        1
#define kSyncPos_LOW                         0
#define kTOC_Sts_SNA                         15
#define kTOC_Sts_TOC_UCF                     7
#define kTOC_Sts_TOC_OCF                     6
#define kTOC_Sts_TOC_MCF                     5
#define kTOC_Sts_TOC_Ready                   3
#define kTOC_Sts_TOC_PNA                     2
#define kTOC_Sts_TOC_TNA                     1
#define kTOC_Sts_TOC_Deactivation            0


#define kPTS_ManoeuvreMode_SNA               7
#define kPTS_ManoeuvreMode_OVER              4
#define kPTS_ManoeuvreMode_PULL_OUT          3
#define kPTS_ManoeuvreMode_PERP              2
#define kPTS_ManoeuvreMode_PARA              1
#define kPTS_ManoeuvreMode_None              0


#define kESS_ENG_ST_SNA                      15
#define kESS_ENG_ST_ENS_ST                   9
#define kESS_ENG_ST_ENS_IHB_LATCH            8
#define kESS_ENG_ST_ENS_DSBL                 7
#define kESS_ENG_ST_ENS_ST_INH               6
#define kESS_ENG_ST_ENS_ST_PRTCT             5
#define kESS_ENG_ST_ENS_STOP_PEND            4
#define kESS_ENG_ST_ENS_RUN                  3
#define kESS_ENG_ST_ENS_RQ_ST                2
#define kESS_ENG_ST_ENS_STOPPED              1


#define kODO_SNA                             16777215


#define kVIN_MSG_SNA                         3
#define kVIN_MSG_VIN_HI                      2
#define kVIN_MSG_VIN_MID                     1
#define kVIN_MSG_VIN_LO                      0


#define kDISPLACEMENT_SNA                    255


#define kNET_CFG_STAT_PT_SNA                 3
#define kNET_CFG_STAT_PT_REQUEST_DATA        2
#define kNET_CFG_STAT_PT_PROGAMMED           1
#define kNET_CFG_STAT_PT_NA                  0


#define kVC_VehCfg1_Stat_SNA                 3
#define kVC_VehCfg1_Stat_REQUEST_DATA        2
#define kVC_VehCfg1_Stat_PROGAMMED           1
#define kVC_VehCfg1_Stat_NA                  0
#define kVC_MODEL_YEAR_SNA                   63
#define kVC_VEH_LINE_SNA                     255
#define kVC_VEH_LINE_VEH_UT                  83
#define kVC_VEH_LINE_VEH_UF                  82
#define kVC_VEH_LINE_VEH_KL                  81
#define kVC_VEH_LINE_VEH_PF                  80
#define kVC_VEH_LINE_VEH_M157                50
#define kVC_VEH_LINE_VEH_WS                  47
#define kVC_VEH_LINE_VEH_WM                  46
#define kVC_VEH_LINE_VEH_RU                  45
#define kVC_VEH_LINE_VEH_LA                  44
#define kVC_VEH_LINE_VEH_ZD                  43
#define kVC_VEH_LINE_VEH_M156                42
#define kVC_VEH_LINE_VEH_LD                  41
#define kVC_VEH_LINE_VEH_DX                  39
#define kVC_VEH_LINE_VEH_WD                  35
#define kVC_VEH_LINE_VEH_DJ                  34
#define kVC_VEH_LINE_VEH_DP                  33
#define kVC_VEH_LINE_VEH_DD                  32
#define kVC_VEH_LINE_VEH_D2                  31
#define kVC_VEH_LINE_VEH_DS                  29
#define kVC_VEH_LINE_VEH_JC                  22
#define kVC_VEH_LINE_VEH_LX                  2
#define kVC_VEH_LINE_VEH_WK                  1
#define kVC_VEH_LINE_VEH_NONE                0
#define kVC_COUNTRY_COUNTRY_SNA              31
#define kVC_COUNTRY_ECE                      21
#define kVC_COUNTRY_S_KOR                    20
#define kVC_COUNTRY_EGYPT                    17
#define kVC_COUNTRY_CHINA                    16
#define kVC_COUNTRY_BRZ                      15
#define kVC_COUNTRY_MEX                      14
#define kVC_COUNTRY_VEN                      13
#define kVC_COUNTRY_GULF                     12
#define kVC_COUNTRY_IND                      11
#define kVC_COUNTRY_AUS                      10
#define kVC_COUNTRY_MLY                      9
#define kVC_COUNTRY_SWISS                    8
#define kVC_COUNTRY_GER                      7
#define kVC_COUNTRY_JPN                      6
#define kVC_COUNTRY_GB                       5
#define kVC_COUNTRY_CND                      4
#define kVC_COUNTRY_EU                       3
#define kVC_COUNTRY_USA                      2
#define kVC_COUNTRY_ROW                      0
#define kVC_XWD__4WD                         3
#define kVC_XWD_ALLWD                        2
#define kVC_XWD__2RR                         1
#define kVC_XWD__2FT                         0
#define kVC_BODY_STYLE_BODY_SNA              15
#define kVC_BODY_STYLE_BODY_4DMP             8
#define kVC_BODY_STYLE_BODY_4DP              7
#define kVC_BODY_STYLE_BODY_2DP              6
#define kVC_BODY_STYLE_BODY_4DH              5
#define kVC_BODY_STYLE_BODY_WAGON            4
#define kVC_BODY_STYLE_BODY_CONV             3
#define kVC_BODY_STYLE_BODY_2DS              2
#define kVC_BODY_STYLE_BODY_4DS              1
#define kVC_BODY_STYLE_BODY_NONE             0


#define kVC_VehCfg3_Stat_SNA                 3
#define kVC_VehCfg3_Stat_REQUEST_DATA        2
#define kVC_VehCfg3_Stat_PROGAMMED           1
#define kVC_VehCfg3_Stat_NA                  0
#define kVC_ChassisType_SNA                  127


#define kVC_VehCfg4_Stat_SNA                 3
#define kVC_VehCfg4_Stat_REQUEST_DATA        2
#define kVC_VehCfg4_Stat_PROGAMMED           1
#define kVC_VehCfg4_Stat_NA                  0
#define kVC_TIRE_CIRCUMF_SNA                 65535


#define kEC_ECUCfg6_Stat_SNA                 3
#define kEC_ECUCfg6_Stat_REQUEST_DATA        2
#define kEC_ECUCfg6_Stat_PROGAMMED           1
#define kEC_ECUCfg6_Stat_NA                  0


#define kNM_Mode_SNA                         255
#define kNM_Mode_ALIVE                       254
#define kNM_Mode_RING                        253
#define kNM_Mode_LHOM                        252
#define kNM_Successor_SNA                    255
#define kNM_Ud_Launch_SNA                    63
#define kNM_Ud_Launch_BROADCAST              4
#define kNM_Ud_Srv_NO_USER_DATA              255
#define kNM_Ud_Srv_AWAKE_BC                  15
#define kNM_Ud_Srv_WAKEUP_SA                 2

#define kWakeupRsn_EPS_SNA                   255
#define kWakeupRsn_EPS_IGN                   1
#define kWakeupRsn_EPS_NETWORK               0
#define kWakeupCnt_SNA                       255

#define kNw_Id_SNA                           255
#define kNw_Id_AUDIO_TELE                    2
#define kNw_Id_BODY                          1
#define kNw_Id_POWERTRAIN                    0


#define kVC_VehCfg5_Stat_SNA                 3
#define kVC_VehCfg5_Stat_REQUEST_DATA        2
#define kVC_VehCfg5_Stat_PROGAMMED           1
#define kVC_VehCfg5_Stat_NA                  0


#define kLongAcceleration_SNA                4095


#define kGr_SNA                              15
#define kGr_KRAFTFREI                        14
#define kGr_P                                13
#define kGr_R2                               12
#define kGr_R                                11
#define kGr_D9                               10
#define kGr_D2P                              9
#define kGr_D8                               8
#define kGr_D7                               7
#define kGr_D6                               6
#define kGr_D5                               5
#define kGr_D4                               4
#define kGr_D3                               3
#define kGr_D2                               2
#define kGr_D1                               1
#define kGr_N                                0


#define kWheelRPM_FL_SNA                     65535
#define kWheelRPM_FR_SNA                     65535


#define kStrClmTrq_SNA                       2047
#define kTOI_Act_Sts_SNA                     15
#define kTOI_Act_Sts_INACT                   8
#define kTOI_Act_Sts_DST_TOI_UCF             7
#define kTOI_Act_Sts_DST_TOI_OCF             6
#define kTOI_Act_Sts_DST_TOI_MCF             5
#define kTOI_Act_Sts_DENIED                  4
#define kTOI_Act_Sts_READY                   3
#define kTOI_Act_Sts_DST_TOI_PNA             2
#define kTOI_Act_Sts_DST_TOI_TNA             1
#define kTOI_Act_Sts_TOI_DEACT               0
#define kStrClmTrqVD_SNA                     0
#define kHALFTorqueOverlayIntActivated_SNA   0


#define kEngOilTemp_SNA                      255


#define kStopLampActive_SNA                  3
#define kStopLampActive_ON                   1
#define kStopLampActive_OFF                  0
#define kEPBSwitchPosition_SNA               3
#define kEPBSwitchPosition_APPLY             2
#define kEPBSwitchPosition_RELEASE           1
#define kEPBSwitchPosition_NONE              0
#define kAutoParkSts_SNA                     3
#define kAutoParkSts_GRADE                   2
#define kAutoParkSts_ON                      1
#define kAutoParkSts_OFF                     0
#define kEPBChimeReq_SNA                     7
#define kEPBChimeReq_T5                      5
#define kEPBChimeReq_T4                      4
#define kEPBChimeReq_T3                      3
#define kEPBChimeReq_T2                      2
#define kEPBChimeReq_T1                      1
#define kEPBChimeReq_NONE                    0
#define kTextDisplay_SNA                     31
#define kTextDisplay_TxtMsg_30               30
#define kTextDisplay_TxtMsg_29               29
#define kTextDisplay_TxtMsg_28               28
#define kTextDisplay_TxtMsg_27               27
#define kTextDisplay_TxtMsg_26               26
#define kTextDisplay_TxtMsg_25               25
#define kTextDisplay_TxtMsg_24               24
#define kTextDisplay_TxtMsg_23               23
#define kTextDisplay_TxtMsg_22               22
#define kTextDisplay_TxtMsg_21               21
#define kTextDisplay_TxtMsg_20               20
#define kTextDisplay_TxtMsg_19               19
#define kTextDisplay_TxtMsg_18               18
#define kTextDisplay_TxtMsg_17               17
#define kTextDisplay_TxtMsg_16               16
#define kTextDisplay_TxtMsg_15               15
#define kTextDisplay_TxtMsg_14               14
#define kTextDisplay_TxtMsg_13               13
#define kTextDisplay_TxtMsg_12               12
#define kTextDisplay_TxtMsg_11               11
#define kTextDisplay_TxtMsg_10               10
#define kTextDisplay_TxtMsg_9                9
#define kTextDisplay_TxtMsg_8                8
#define kTextDisplay_TxtMsg_7                7
#define kTextDisplay_TxtMsg_6                6
#define kTextDisplay_TxtMsg_5                5
#define kTextDisplay_TxtMsg_4                4
#define kTextDisplay_TxtMsg_3                3
#define kTextDisplay_TxtMsg_2                2
#define kTextDisplay_TxtMsg_1                1
#define kTextDisplay_NONE                    0
#define kEnableDecelerationReq_ERROR         3
#define kEnableDecelerationReq_OK            0
#define kFunctionLamp_SNA                    3
#define kFunctionLamp_BLINK                  2
#define kFunctionLamp_CONT                   1
#define kFunctionLamp_OFF                    0
#define kEPBWarningLampReq_SNA               3
#define kEPBWarningLampReq_BLINK             2
#define kEPBWarningLampReq_CONT              1
#define kEPBWarningLampReq_OFF               0


#define kCFG_FEATURE_CFG_CHMSL_LINES         105
#define kCFG_FEATURE_CFG_EPS                 104
#define kCFG_FEATURE_CFG_TorqueUnit          103
#define kCFG_FEATURE_CFG_PowerUnit           102
#define kCFG_FEATURE_CFG_TemperatureUnit     101
#define kCFG_FEATURE_CFG_CapacityUnit        100
#define kCFG_FEATURE_CFG_ConsumptionUnit     99
#define kCFG_FEATURE_CFG_DistanceUnit        98
#define kCFG_FEATURE_CFG_SpeedUnit           97
#define kCFG_FEATURE_CFG_PressureUnit        96
#define kCFG_FEATURE_CFG_UNIT_DEFAULT        95
#define kCFG_FEATURE_CFG_PTO_REM_Throttle    94
#define kCFG_FEATURE_CFG_LDWTRQ              93
#define kCFG_FEATURE_CFG_AUX5                91
#define kCFG_FEATURE_CFG_AUX4                90
#define kCFG_FEATURE_CFG_AUX3                89
#define kCFG_FEATURE_CFG_AUX2                88
#define kCFG_FEATURE_CFG_AUX1                87
#define kCFG_FEATURE_CFG_PLG                 86
#define kCFG_FEATURE_CFG_PTS_RR_VOL          84
#define kCFG_FEATURE_CFG_PTS_FT_VOL          83
#define kCFG_FEATURE_CFG_PTS_RR              82
#define kCFG_FEATURE_CFG_PTS_FT              81
#define kCFG_FEATURE_CFG_TRLR_NAME           77
#define kCFG_FEATURE_CFG_TRLR_TYP            76
#define kCFG_FEATURE_RLE_HORN                73
#define kCFG_FEATURE_RLE_LIGHT               72
#define kCFG_FEATURE_DIMMER                  71
#define kCFG_FEATURE_RVC_GRID                70
#define kCFG_FEATURE_CFG_MAX_PTO_VEH_SPEED   69
#define kCFG_FEATURE_CFG_PTO_Auto_Resume     68
#define kCFG_FEATURE_CFG_PTO_Type            67
#define kCFG_FEATURE_CFG_PTO_RPM3            66
#define kCFG_FEATURE_CFG_PTO_RPM2            65
#define kCFG_FEATURE_CFG_PTO_RPM1            64
#define kCFG_FEATURE_CFG_PTO_SINGLE_RPM      63
#define kCFG_FEATURE_CFG_PTO_MODE            62
#define kCFG_FEATURE_CFG_TRANSPORT           61
#define kCFG_FEATURE_CFG_NORMAL_DCS          59
#define kCFG_FEATURE_OIL                     58
#define kCFG_FEATURE_CFG_LDW                 57
#define kCFG_FEATURE_CFG_ASCM_WMO            55
#define kCFG_FEATURE_CFG_ALIGNMENT           54
#define kCFG_FEATURE_CFG_TRLR                53
#define kCFG_FEATURE_JACK                    52
#define kCFG_FEATURE_AERO                    51
#define kCFG_FEATURE_PASS_WIN_LKOUT          50
#define kCFG_FEATURE_CFG_ECMM                49
#define kCFG_FEATURE_CFG_HDLP_DROP           48
#define kCFG_FEATURE_CFG_FCW_SENS            47
#define kCFG_FEATURE_CFG_FUEL_SAV            46
#define kCFG_FEATURE_CFG_BELT_SLAK           45
#define kCFG_FEATURE_CFG_PRE_SAFE            44
#define kCFG_FEATURE_CFG_FCW                 43
#define kCFG_FEATURE_CFG_CMS                 42
#define kCFG_FEATURE_CFG_AUTO_RELK           41
#define kCFG_FEATURE_CFG_DCS                 40
#define kCFG_FEATURE_CFG_SOUND_RS            39
#define kCFG_FEATURE_CFG_DSS                 38
#define kCFG_FEATURE_CFG_WAL                 37
#define kCFG_FEATURE_CFG_PE                  36
#define kCFG_FEATURE_CFG_BSD                 35
#define kCFG_FEATURE_CFG_AFS                 34
#define kCFG_FEATURE_CFG_HILL_ST             33
#define kCFG_FEATURE_CFG_NAV_TBYT            32
#define kCFG_FEATURE_CFG_VOICE_COMF          31
#define kCFG_FEATURE_CFG_CMP_VAR             30
#define kCFG_FEATURE_CFG_CMP_CAL             29
#define kCFG_FEATURE_REST_FACT_DEF           28
#define kCFG_FEATURE_CFG_AHB                 27
#define kCFG_FEATURE_CFG_DRL_ON              26
#define kCFG_FEATURE_CFG_GLBL_DN_WIN         25
#define kCFG_FEATURE_CFG_GLBL_UP_WIN         24
#define kCFG_FEATURE_CFG_ILL_ENTRY           23
#define kCFG_FEATURE_CFG_ILL_APRCH           22
#define kCFG_FEATURE_CFG_TILT_IN_REV         21
#define kCFG_FEATURE_CFG_LO_VEH              20
#define kCFG_FEATURE_CFG_EASY_EXIT           19
#define kCFG_FEATURE_CFG_REM_MEM             18
#define kCFG_FEATURE_CFG_ACC_DLY             16
#define kCFG_FEATURE_CFG_HL_WPR              15
#define kCFG_FEATURE_CFG_HL_DLY              14
#define kCFG_FEATURE_CFG_AUTO_WPR            13
#define kCFG_FEATURE_CFG_SRV_INTV            12
#define kCFG_FEATURE_CFG_US_METRIC           11
#define kCFG_FEATURE_CFG_LANG                10
#define kCFG_FEATURE_CFG_PARK_ASSIST         9
#define kCFG_FEATURE_CFG_DrAlrPrsnt          8
#define kCFG_FEATURE_CFG_FLASH_LK            7
#define kCFG_FEATURE_CFG_HORN_DUR            6
#define kCFG_FEATURE_CFG_SOUND_LK            5
#define kCFG_FEATURE_CFG_DRV_FST             4
#define kCFG_FEATURE_CFG_DLY_LK              3
#define kCFG_FEATURE_CFG_AUTO_UNLK           2
#define kCFG_FEATURE_CFG_AUTO_LK             1
#define kCFG_FEATURE_CFG_NONE                0
#define kCFG_STAT_RQ_CFG_SPEC                3
#define kCFG_STAT_RQ_CFG_ENBL                2
#define kCFG_STAT_RQ_CFG_DSBL                1
#define kCFG_STAT_RQ_CFG_DEF                 0


#define kCFG_FEATURE_C_CFG_CHMSL_LINES       105
#define kCFG_FEATURE_C_CFG_EPS               104
#define kCFG_FEATURE_C_CFG_TorqueUnit        103
#define kCFG_FEATURE_C_CFG_PowerUnit         102
#define kCFG_FEATURE_C_CFG_TemperatureUnit   101
#define kCFG_FEATURE_C_CFG_CapacityUnit      100
#define kCFG_FEATURE_C_CFG_ConsumptionUnit   99
#define kCFG_FEATURE_C_CFG_DistanceUnit      98
#define kCFG_FEATURE_C_CFG_SpeedUnit         97
#define kCFG_FEATURE_C_CFG_PressureUnit      96
#define kCFG_FEATURE_C_CFG_UNIT_DEFAULT      95
#define kCFG_FEATURE_C_CFG_PTO_REM_Throttle  94
#define kCFG_FEATURE_C_CFG_LDWTRQ            93
#define kCFG_FEATURE_C_CFG_AUX5              91
#define kCFG_FEATURE_C_CFG_AUX4              90
#define kCFG_FEATURE_C_CFG_AUX3              89
#define kCFG_FEATURE_C_CFG_AUX2              88
#define kCFG_FEATURE_C_CFG_AUX1              87
#define kCFG_FEATURE_C_CFG_PLG               86
#define kCFG_FEATURE_C_CFG_PTS_RR_VOL        84
#define kCFG_FEATURE_C_CFG_PTS_FT_VOL        83
#define kCFG_FEATURE_C_CFG_PTS_RR            82
#define kCFG_FEATURE_C_CFG_PTS_FT            81
#define kCFG_FEATURE_C_CFG_TRLR_NAME         77
#define kCFG_FEATURE_C_CFG_TRLR_TYP          76
#define kCFG_FEATURE_C_RLE_HORN              73
#define kCFG_FEATURE_C_RLE_LIGHT             72
#define kCFG_FEATURE_C_DIMMER                71
#define kCFG_FEATURE_C_RVC_GRID              70
#define kCFG_FEATURE_C_CFG_MAX_PTO_VEH_SPEED 69
#define kCFG_FEATURE_C_CFG_PTO_Auto_Resume   68
#define kCFG_FEATURE_C_CFG_PTO_Type          67
#define kCFG_FEATURE_C_CFG_PTO_RPM3          66
#define kCFG_FEATURE_C_CFG_PTO_RPM2          65
#define kCFG_FEATURE_C_CFG_PTO_RPM1          64
#define kCFG_FEATURE_C_CFG_PTO_SINGLE_RPM    63
#define kCFG_FEATURE_C_CFG_PTO_MODE          62
#define kCFG_FEATURE_C_CFG_TRANSPORT         61
#define kCFG_FEATURE_C_CFG_NORMAL_DCS        59
#define kCFG_FEATURE_C_OIL                   58
#define kCFG_FEATURE_C_CFG_LDW               57
#define kCFG_FEATURE_C_CFG_ASCM_WMO          55
#define kCFG_FEATURE_C_CFG_ALIGNMENT         54
#define kCFG_FEATURE_C_CFG_TRLR              53
#define kCFG_FEATURE_C_JACK                  52
#define kCFG_FEATURE_C_AERO                  51
#define kCFG_FEATURE_C_PASS_WIN_LKOUT        50
#define kCFG_FEATURE_C_CFG_ECMM              49
#define kCFG_FEATURE_C_CFG_HDLP_DROP         48
#define kCFG_FEATURE_C_CFG_FCW_SENS          47
#define kCFG_FEATURE_C_CFG_FUEL_SAV          46
#define kCFG_FEATURE_C_CFG_BELT_SLAK         45
#define kCFG_FEATURE_C_CFG_PRE_SAFE          44
#define kCFG_FEATURE_C_CFG_FCW               43
#define kCFG_FEATURE_C_CFG_CMS               42
#define kCFG_FEATURE_C_CFG_AUTO_RELK         41
#define kCFG_FEATURE_C_CFG_DCS               40
#define kCFG_FEATURE_C_CFG_SOUND_RS          39
#define kCFG_FEATURE_C_CFG_DSS               38
#define kCFG_FEATURE_C_CFG_WAL               37
#define kCFG_FEATURE_C_CFG_PE                36
#define kCFG_FEATURE_C_CFG_BSD               35
#define kCFG_FEATURE_C_CFG_AFS               34
#define kCFG_FEATURE_C_CFG_HILL_ST           33
#define kCFG_FEATURE_C_CFG_NAV_TBYT          32
#define kCFG_FEATURE_C_CFG_VOICE_COMF        31
#define kCFG_FEATURE_C_CFG_CMP_VAR           30
#define kCFG_FEATURE_C_CFG_CMP_CAL           29
#define kCFG_FEATURE_C_REST_FACT_DEF         28
#define kCFG_FEATURE_C_CFG_AHB               27
#define kCFG_FEATURE_C_CFG_DRL_ON            26
#define kCFG_FEATURE_C_CFG_GLBL_DN_WIN       25
#define kCFG_FEATURE_C_CFG_GLBL_UP_WIN       24
#define kCFG_FEATURE_C_CFG_ILL_ENTRY         23
#define kCFG_FEATURE_C_CFG_ILL_APRCH         22
#define kCFG_FEATURE_C_CFG_TILT_IN_REV       21
#define kCFG_FEATURE_C_CFG_LO_VEH            20
#define kCFG_FEATURE_C_CFG_EASY_EXIT         19
#define kCFG_FEATURE_C_CFG_REM_MEM           18
#define kCFG_FEATURE_C_CFG_ACC_DLY           16
#define kCFG_FEATURE_C_CFG_HL_WPR            15
#define kCFG_FEATURE_C_CFG_HL_DLY            14
#define kCFG_FEATURE_C_CFG_AUTO_WPR          13
#define kCFG_FEATURE_C_CFG_SRV_INTV          12
#define kCFG_FEATURE_C_CFG_US_METRIC         11
#define kCFG_FEATURE_C_CFG_LANG              10
#define kCFG_FEATURE_C_CFG_PARK_ASSIST       9
#define kCFG_FEATURE_C_CFG_DrAlrPrsnt        8
#define kCFG_FEATURE_C_CFG_FLASH_LK          7
#define kCFG_FEATURE_C_CFG_HORN_DUR          6
#define kCFG_FEATURE_C_CFG_SOUND_LK          5
#define kCFG_FEATURE_C_CFG_DRV_FST           4
#define kCFG_FEATURE_C_CFG_DLY_LK            3
#define kCFG_FEATURE_C_CFG_AUTO_UNLK         2
#define kCFG_FEATURE_C_CFG_AUTO_LK           1
#define kCFG_FEATURE_C_CFG_NONE              0
#define kCFG_STAT_RQ_C_CFG_SPEC              3
#define kCFG_STAT_RQ_C_CFG_ENBL              2
#define kCFG_STAT_RQ_C_CFG_DSBL              1
#define kCFG_STAT_RQ_C_CFG_DEF               0


#define kEPS_MODE_REQ_SNA                    7
#define kEPS_MODE_REQ_LAST                   3
#define kEPS_MODE_REQ_MODE_3                 2
#define kEPS_MODE_REQ_MODE_2                 1
#define kEPS_MODE_REQ_MODE_1                 0




#define kVC_VehCfg2_Stat_SNA                 3
#define kVC_VehCfg2_Stat_REQUEST_DATA        2
#define kVC_VehCfg2_Stat_PROGAMMED           1
#define kVC_VehCfg2_Stat_NA                  0




/* -----------------------------------------------------------------------------
    &&&~ Message Unions
 ----------------------------------------------------------------------------- */

typedef union _c_D_RS_EPS_bufTag
{
  vuint8 _c[8];
  _c_D_RS_EPS_msgType D_RS_EPS;
} _c_D_RS_EPS_buf;
typedef union _c_ECU_APPL_EPS_bufTag
{
  vuint8 _c[8];
  _c_ECU_APPL_EPS_msgType ECU_APPL_EPS;
} _c_ECU_APPL_EPS_buf;
typedef union _c_APPL_ECU_EPS_bufTag
{
  vuint8 _c[8];
  _c_APPL_ECU_EPS_msgType APPL_ECU_EPS;
} _c_APPL_ECU_EPS_buf;


/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_D_RS_EPS_buf V_MEMRAM2 D_RS_EPS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ECU_APPL_EPS_buf V_MEMRAM2 ECU_APPL_EPS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_APPL_ECU_EPS_buf V_MEMRAM2 APPL_ECU_EPS;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 1 START */
V_MEMRAM0 extern  V_MEMRAM1_NEAR vuint32 V_MEMRAM2_NEAR nmSendMess[2];
/* RAM CATEGORY 1 END */






/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 103168731
      #error "The magic number of the generated file <C:\Synergy_WorkArea\ESG_Dev_65\Chrysler_LWR_EPS_TMS570-tzj9qy\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\drv_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 103168731
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DRV_PAR_H__ */
