/* -----------------------------------------------------------------------------
  Filename:    hw_config.h
  Description: Toolversion: 01.00.35.01.21.00.21.01.00.00
               
               Serial Number: CBD1210021
               Customer Info: Nxtr
                              Package: CBD_Chrysler_SLP1_UDS_Sgl
                              Micro: TexasInstruments TMS570 - TMX570LS0805APGEQQ1
                              Compiler: Texas Instruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Hw_Settings_Dc
               
               Configuration   : C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\Chrsyler_SLP1_EPS.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570PSFC66
               
               Channel "Channel0":
                       Databasefile: C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\Tools\AsrProject\GENy\CAN C v1232 EPS.dbc
                       Bussystem:    CAN
                       Manufacturer: DaimlerChrysler
                       Node:         EPS

  Generated by , 2012-12-11  16:14:27
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__HW_CONFIG_H__)
#define __HW_CONFIG_H__

/* -----------------------------------------------------------------------------
    &&&~ Availible Types
 ----------------------------------------------------------------------------- */

/* Transceivers */
#define UnknownTransceiver                   0
#define UNKNOWNTRS                           0
#define TJA1040                              1
#define TJA1041                              2
#define MC33742                              3
/* Chokes */
#define UnknownChoke                         0
#define UNKNOWNCHOKE                         0
#define B82790_S0513_N201                    1
#define B82793_S0513_N201                    2
#define B82799_S0333_N1                      3
#define B82789_S0223_N1                      4
#define B82789_S0223_N2                      5
#define DK2x50uH_05A                         6
#define ST2001                               7
#define DR332_513                            8
#define ZJYS81R5_2PL51T_G                    9
#define ACT4532_102_2PT                      10
#define TF0513S                              11
#define TX8111T                              12
#define M3001                                13
/* Oscillators */
#define UnknownOscillator                    0
#define OscUndefined                         0
#define CRYSTAL                              1
/* Communication types */
#define UnknownCommunication                 0
#define CommUndefined                        0
#define CommCAN                              1
#define CommLIN                              2


/* -----------------------------------------------------------------------------
    &&&~ Current Settings
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ System specific
 ----------------------------------------------------------------------------- */

#define HW_CHANNELS                          1
#define HW_CONTROLLER                        112
#define HW_DERIVATIVE                        2
#define HW_COMPILER                          25
#define HW_OSCILLATOR                        OscUndefined
#define HW_OSCILLATOR_CLOCK                  80000


/* -----------------------------------------------------------------------------
    &&&~ Channel specific
 ----------------------------------------------------------------------------- */

#define HW_CHOKE
#define HW_COMMUNICATION_TYPE                CommUndefined
#define HW_TRANSCEIVER                       UNKNOWNTRS
#define HW_RESISTOR                          0
#define HW_CAN_BTR0                          201
#define HW_CAN_BTR1                          58
#define HW_CAN_BTR2                          0
#define HW_CAN_BTR3                          0





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 114480237
      #error "The magic number of the generated file <C:\Synergy\Chrysler_LWR_EPS_TMS570-zz4r1x\Chrysler_LWR_EPS_TMS570\SwProject\Source\_GenData\hw_config.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 114480237
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __HW_CONFIG_H__ */
