#if !defined(__NM_USERDATA_CFG_H__)
#define __NM_USERDATA_CFG_H__

#define VGEN_VERSION_NM_OSEK_D_UD_MAIN    2
#define VGEN_VERSION_NM_OSEK_D_UD_SUB     6
#define VGEN_VERSION_NM_OSEK_D_UD_RELEASE 0


#define NM_ENABLE_USERDATA_TASK
#define NM_ENABLE_SEND_ALIVE_BROADCAST
#define NM_ENABLE_SEND_RING_BROADCAST
#define NM_ENABLE_USERDATA_DPM_SERVICE
#endif /* __NM_USERDATA_CFG_H__ */
