/*****************************************************************************
* Copyright 2010 Nxtr Automotive, All Rights Reserved.
* Nxtr Confidential
*
* Module File Name  : EcuStartup.c
* Module Description: AUTOSAR Startup Sequence
* Product           : Gen II Plus - EA3.0
* Author            : Jeremy Warmbier
*****************************************************************************/
/* Version Control:
 * Date Created:      Wed Apr 13 12:17:00 2011
 * %version:          EA3#17.1.4 %
 * %derived_by:       gz324f %
 * %date_modified:    Thu Feb  6 10:07:17 2014 %
 *---------------------------------------------------------------------------------------------------------------------
 * Date      Rev      Author         Change Description                                                        SCR #
 * -------   -------  --------  ---------------------------------------------------------------------------  ----------
 * 07/13/12  1        BG        Initial Version
 * 07/20/12  2		  BG		Initial Version
 * 07/31/12  3		  SAH		Updates for new microdiag integration
 * 08/09/12  4        SAH       included default config data
 * 08/12/12  5        SAH       added include paths
 * 01/04/13  6        SAH       Clean up, removed if 0
 * 01/16/13  7        SAH       Added EnableCaninterrupt, clean up
 * 01/30/13	 9		  SAH		Added cclinit function
 * 02/21/13  10		  SAH		Added ePWM_Init1 function
 * 02/26/13  11		  SAH		Added ePWM.h include
 * 07/01/13  13		  JJW		Added NvMProxy_Init
 * 07/02/13  14		  JJW		Moved Gpt_Init to accomodate use of privileged register API
 * 07/10/13  15		  JJW		Added required trusted/non-trusted function calls for application split support
 * 07/11/13  16		  JJW		Added uDiag Init functions requiring privileged mode execution
 * 07/22/13  17		  JJW		Added deprecated block processing wait loop prior to NvMProxy_Init
 * 10/21/13  17.1.1	  SAH		Added Dem_Init1 call to initialize frfm data
 * 01/18/14  17.1.2	  SAH		Removed EnableESMInterrupt(now in udiag).
 * 02/05/14  17.1.3	  SAH		Removed Deprecated eeprom block jobfinished wait
 * 08/12/16  17.1.4	  SV		Updated for EEPROM to FEE change
 */


/**************************************************************************************************
* Include files
**************************************************************************************************/

/*
 * Description: The V_Cfg header is generated by the generation tool. Important 
 *              information like CPU and compiler type, manufacturer information
 *              and a list of currently used CANbedded modules is defined here.
 */
#include "Std_Types.h"
#include "V_Cfg.h"
#include "SchM_Cfg.h"
#include "EcuStartup.h"
#include "NvM_Cfg.h"
#include "ApplCallbacks.h"
#include "Nhet.h"
#include "Adc2.h"
#include "SrlComSrvc.h"
#include "PwmCdd.h"
#include "Ap_DfltConfigData.h"
#include "Interrupts.h"
#include "desc.h"
#include "SystemTime.h"
#include "FlsTst.h"
#include "Nm_basic.h"
#include "ccl.h"
#include "ccl_inc.h"
#include "Cd_FeeIf.h"
#include "Metrics.h"


/*****************************************************************************
 * Include the CANbedded files 
 *****************************************************************************/
#if defined( VGEN_ENABLE_SYSSERVICE_ASRDET )
# include "Det.h"
#endif /* VGEN_ENABLE_SYSSERVICE_ASRDET */


# include "NvM.h"
# include "EcuM.h"
# include "SchM.h"
# include "Dem.h"
# include "MemIf_Types.h"
# include "Adc.h"
# include "Gpt.h"
# include "Mcu.h"
# include "Port.h"
# include "IoHwAb.h"
# include "XcpProf.h"
# include "CDD_Func.h"
# include "ePWM.h"
#include "Ap_ApXcp.h"
#include "NtWrap.h"

/* Constants to configure deprecated block wait */



extern FUNC(void, AUTOMATIC) appdesc_init(void);

/*****************************************************************************
  * Name:        main
  * Description: 
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
int main(void) 
{
	Metrics_Init();
	osInitialize();
	EcuM_Init();
}

/*****************************************************************************
  * Name:        EcuStartup_Init1
  * Description: Initialization executed prior to OS start  
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
void EcuStartup_Init1(void) 
{
#if defined( VGEN_ENABLE_SYSSERVICE_ASRDET )
  Det_Init();
  Det_Start();  /* must be initialized before other components */
#endif

  SchM_InitMemory();
  ApXcp_Init();
  
  /* uDiag Init Functions */
  FlsTst_Init(&FlsTst_Runtime);
  uDiagCCRM_Init();
  uDiagClockMonitor_Init();
  uDiagECC_Init();
  uDiagESM_Init();
  uDiagIOMM_Init();
  uDiagParity_Init();
  uDiagStaticRegs_Init();
  uDiagVIM_Init();
  
  Nhet_Init1();
  ePWM_Init1();
}

/*****************************************************************************
  * Name:        EcuStartup_Init2
  * Description: Initialization executed after OS start  
  * Inputs:      None 
  * Outputs:     None
  *
*****************************************************************************/
void EcuStartup_Init2(void)
{


  Gpt_Init(&Gpt_Runtime);
  SystemTime_Init();
  NtWrapC_Adc_Init();
  Call_Adc2_Init1();
  Call_PwmCdd_Init();

  EnableCRCInterrupt();
  Port_Init(&Port_Runtime);
  Metrics_Init2();
  CclInitPowerOn();

  NvM_Init();
  TWrapC_FeeIf_Init();
  /* Added the suspend/resume calls around the readall. Further analsis will need to be done to see if the resume
   * call should be applied later in start up */
  TWrapC_TI_Fee_SuspendResumeErase(Suspend_Erase);
  NvM_ReadAll();
  /* TODO:  See if startup can be optimized to minimize NVM waiting */
  Appl_WaitNvMReady(0, TRUE);
  TWrapC_TI_Fee_SuspendResumeErase(Resume_Erase);
  DfltConfigData_Init1();


 /* After the NvM driver has completed initializing the unsecured memory, execute the NvMProxy_Init to
  * transfer the data to secured memory.
  * Execution of the NvMProxy_Init function requires a trusted function call to place the system into a
  * privileged state that allows writing to the secured memory regions.
  *
  */  
  Call_NvMProxy_Init();

  
  SrlComSrvc_Init1();
  Dem_Init1();
  FrfmPowerUp();
  NmBasicInitPowerOn();


  EnableCanInterrupt();
  
  appdesc_init();
}


