#ifndef AP_WHLIMBREJ_CFG_H
#define AP_WHLIMBREJ_CFG_H

extern void Rte_Call_WhlImbRej_Per1_CP0_CheckpointReached(void);
extern void Rte_Call_WhlImbRej_Per1_CP1_CheckpointReached(void);
extern void Rte_Call_WhlImbRej_Per2_CP0_CheckpointReached(void);
extern void Rte_Call_WhlImbRej_Per2_CP1_CheckpointReached(void);
extern void Rte_Call_WhlImbRej_Per3_CP0_CheckpointReached(void);
extern void Rte_Call_WhlImbRej_Per3_CP1_CheckpointReached(void);

#endif